//! Write worksheet models to supported XLSX workbook parts.

use std::collections::{BTreeMap, BTreeSet};

use loom_package::zip::PackageArchive;

use crate::style::{CellAlignment, CellStyle};
use crate::{CellRef, ChartKind, Sheet, SheetChart, SheetObject, SheetObjectKind};

use super::cell_refs::{chart_sheet_reference, column_letters};
use super::styles::{apply_exported_styles, render_styles_xml, rgb_for_fill, XfKey};
use super::xml::{xml_escape_attr, xml_escape_text};
use super::{CHART_NS, DRAWINGML_NS, DRAWING_NS, EMU_PER_PIXEL, PACKAGE_REL_NS, REL_NS};

/// Export every worksheet with formulas, cell formatting, and supported
/// drawing objects represented in OOXML parts. The legacy exporter supplies
/// the well-tested cell/value package; this layer adds the richer parts and
/// rewrites the package without losing the base workbook metadata.
pub fn export_xlsx_sheets(sheets: &[Sheet]) -> Result<Vec<u8>, String> {
    if sheets.is_empty() {
        return Err("xlsx export needs at least one sheet".to_string());
    }
    let evaluated = crate::workbook::evaluate_workbook(sheets);
    let data = sheets
        .iter()
        .zip(evaluated.iter())
        .map(|(sheet, values)| crate::sheet_to_xlsx_data(sheet, values))
        .collect::<Vec<_>>();
    let exported_sheet_names = crate::unique_xlsx_sheet_names(&data)?.names;
    let base = crate::export_xlsx_workbook(&data)?;
    let base_archive = PackageArchive::from_bytes(&base)
        .map_err(|e| format!("xlsx export base archive failed: {e}"))?;

    let mut style_keys = vec![XfKey {
        style: CellStyle::default(),
        alignment: CellAlignment::General,
    }];
    for sheet in sheets {
        let mut coordinates = BTreeSet::new();
        coordinates.extend(sheet.cells.keys().copied());
        coordinates.extend(sheet.styles.keys().copied());
        coordinates.extend(sheet.alignments.keys().copied());
        for cell in coordinates {
            let key = XfKey::from_sheet(sheet, cell);
            if !style_keys.contains(&key) {
                style_keys.push(key);
            }
        }
    }
    let style_ids = style_keys
        .iter()
        .enumerate()
        .map(|(id, key)| (*key, id))
        .collect::<Vec<_>>();
    let styles_xml = render_styles_xml(&style_keys);
    let mut replacements = BTreeMap::<String, Vec<u8>>::new();
    let mut extras = BTreeMap::<String, Vec<u8>>::new();
    let mut image_extensions = BTreeSet::new();

    for (index, sheet) in sheets.iter().enumerate() {
        let sheet_path = format!("xl/worksheets/sheet{}.xml", index + 1);
        let sheet_xml = base_archive
            .get(&sheet_path)
            .ok_or_else(|| format!("missing generated worksheet part {sheet_path}"))?;
        let sheet_xml = std::str::from_utf8(sheet_xml)
            .map_err(|_| format!("{sheet_path} is not valid UTF-8"))?;
        let styled_xml = apply_exported_styles(sheet_xml, sheet, &style_ids);
        let has_drawing = sheet.chart.is_some() || !sheet.objects.is_empty();
        if has_drawing {
            let drawing_number = index + 1;
            let (drawing_xml, drawing_rels, chart_parts, image_parts, extensions) =
                render_drawing_parts(sheet, index + 1, &exported_sheet_names[index])?;
            image_extensions.extend(extensions);
            extras.insert(
                format!("xl/drawings/drawing{drawing_number}.xml"),
                drawing_xml.into_bytes(),
            );
            extras.insert(
                format!("xl/drawings/_rels/drawing{drawing_number}.xml.rels"),
                drawing_rels.into_bytes(),
            );
            for (path, xml) in chart_parts {
                extras.insert(path, xml.into_bytes());
            }
            for (path, bytes) in image_parts {
                extras.insert(path, bytes);
            }
            // `worksheet` is generated by the legacy exporter without the
            // office-document relationship namespace. Declare it on the
            // element that owns `r:id` so independent OOXML parsers can
            // resolve the prefix.
            let drawing_relationship = format!("<drawing xmlns:r=\"{REL_NS}\" r:id=\"rId1\"/>");
            let with_drawing = styled_xml.replace(
                "</worksheet>",
                &format!("{drawing_relationship}</worksheet>"),
            );
            extras.insert(
                format!("xl/worksheets/_rels/sheet{}.xml.rels", index + 1),
                worksheet_drawing_rels(drawing_number).into_bytes(),
            );
            replacements.insert(sheet_path, with_drawing.into_bytes());
        } else {
            replacements.insert(sheet_path, styled_xml.into_bytes());
        }
    }

    let content_types = base_archive
        .get("[Content_Types].xml")
        .ok_or_else(|| "generated xlsx is missing [Content_Types].xml".to_string())?;
    let content_types = std::str::from_utf8(content_types)
        .map_err(|_| "[Content_Types].xml is not valid UTF-8".to_string())?;
    replacements.insert(
        "[Content_Types].xml".to_string(),
        render_content_types(content_types, sheets, &image_extensions).into_bytes(),
    );
    extras.insert("xl/styles.xml".to_string(), styles_xml.into_bytes());

    let mut archive = PackageArchive::new();
    for path in base_archive.paths() {
        if let Some(bytes) = replacements.remove(path) {
            archive
                .add(path, bytes)
                .map_err(|e| format!("xlsx export failed: {e}"))?;
        } else if path != "xl/styles.xml" {
            archive
                .add(path, base_archive.get(path).unwrap_or_default().to_vec())
                .map_err(|e| format!("xlsx export failed: {e}"))?;
        }
    }
    for (path, bytes) in replacements {
        archive
            .add(&path, bytes)
            .map_err(|e| format!("xlsx export failed: {e}"))?;
    }
    for (path, bytes) in extras {
        archive
            .add(&path, bytes)
            .map_err(|e| format!("xlsx export failed: {e}"))?;
    }
    archive
        .to_bytes()
        .map_err(|e| format!("xlsx export failed: {e}"))
}

type DrawingParts = (
    String,
    String,
    Vec<(String, String)>,
    Vec<(String, Vec<u8>)>,
    BTreeSet<String>,
);

fn render_drawing_parts(
    sheet: &Sheet,
    sheet_number: usize,
    exported_sheet_name: &str,
) -> Result<DrawingParts, String> {
    let mut drawing = String::new();
    let mut drawing_rels = String::new();
    let mut chart_parts = Vec::new();
    let mut image_parts = Vec::new();
    let mut image_extensions = BTreeSet::new();
    let mut rel_id = 1usize;
    let mut object_id = 1usize;

    if let Some(chart) = &sheet.chart {
        let chart_rel = format!("rId{rel_id}");
        rel_id += 1;
        drawing_rels.push_str(&format!(
            "<Relationship Id=\"{chart_rel}\" Type=\"{CHART_REL_TYPE}\" Target=\"../charts/chart{sheet_number}.xml\"/>"
        ));
        chart_parts.push((
            format!("xl/charts/chart{sheet_number}.xml"),
            render_chart_xml(sheet, chart, exported_sheet_name),
        ));
        drawing.push_str(&one_cell_anchor(
            CellRef { row: 0, col: 3 },
            560,
            320,
            &format!(
                "<xdr:graphicFrame macro=\"\"><xdr:nvGraphicFramePr><xdr:cNvPr id=\"{object_id}\" name=\"Chart {object_id}\"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm/><a:graphic><a:graphicData uri=\"{CHART_GRAPHIC_URI}\"><c:chart r:id=\"{chart_rel}\"/></a:graphicData></a:graphic></xdr:graphicFrame>"
            ),
        ));
        object_id += 1;
    }

    for (object_index, object) in sheet.objects.iter().enumerate() {
        match object.kind {
            SheetObjectKind::Shape => {
                drawing.push_str(&one_cell_anchor(
                    object.anchor,
                    object.width,
                    object.height,
                    &format!(
                        "<xdr:sp><xdr:nvSpPr><xdr:cNvPr id=\"{object_id}\" name=\"Shape {object_id}\" descr=\"{}\"/><xdr:cNvSpPr txBox=\"0\"/></xdr:nvSpPr><xdr:spPr><a:solidFill><a:srgbClr val=\"{}\"/></a:solidFill><a:ln/></xdr:spPr><xdr:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang=\"en-US\"/><a:t>{}</a:t></a:r></a:p></xdr:txBody></xdr:sp>",
                        xml_escape_attr(&object.label),
                        rgb_for_fill(object.fill),
                        xml_escape_text(&object.label),
                    ),
                ));
                object_id += 1;
            }
            SheetObjectKind::Image => {
                let payload = object
                    .embedded
                    .clone()
                    .or_else(|| std::fs::read(&object.path).ok())
                    .ok_or_else(|| {
                        if object.path.trim().is_empty() {
                            "image object has no embedded payload or source path".to_string()
                        } else {
                            format!("unable to read image {}", object.path)
                        }
                    })?;
                let extension = image_extension_for_object(object);
                image_extensions.insert(extension.to_string());
                let filename = format!("sheet{sheet_number}-object{object_index}.{extension}");
                let image_rel = format!("rId{rel_id}");
                rel_id += 1;
                drawing_rels.push_str(&format!(
                    "<Relationship Id=\"{image_rel}\" Type=\"{IMAGE_REL_TYPE}\" Target=\"../media/{filename}\"/>"
                ));
                image_parts.push((format!("xl/media/{filename}"), payload));
                drawing.push_str(&one_cell_anchor(
                    object.anchor,
                    object.width,
                    object.height,
                    &format!(
                        "<xdr:pic><xdr:nvPicPr><xdr:cNvPr id=\"{object_id}\" name=\"Image {object_id}\" descr=\"{}\"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip r:embed=\"{image_rel}\"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic>",
                        xml_escape_attr(&object.label),
                    ),
                ));
                object_id += 1;
            }
        }
    }
    Ok((
        format!(
            "<?xml version=\"1.0\"?><xdr:wsDr xmlns:xdr=\"{DRAWING_NS}\" xmlns:a=\"{DRAWINGML_NS}\" xmlns:c=\"{CHART_NS}\" xmlns:r=\"{REL_NS}\">{drawing}</xdr:wsDr>"
        ),
        format!(
            "<?xml version=\"1.0\"?><Relationships xmlns=\"{PACKAGE_REL_NS}\">{drawing_rels}</Relationships>"
        ),
        chart_parts,
        image_parts,
        image_extensions,
    ))
}

fn one_cell_anchor(cell: CellRef, width: u32, height: u32, content: &str) -> String {
    let cx = (width.max(1) as f32 * EMU_PER_PIXEL).round() as u64;
    let cy = (height.max(1) as f32 * EMU_PER_PIXEL).round() as u64;
    format!(
        "<xdr:oneCellAnchor><xdr:from><xdr:col>{}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>{}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx=\"{cx}\" cy=\"{cy}\"/>{content}<xdr:clientData/></xdr:oneCellAnchor>",
        cell.col, cell.row
    )
}

fn render_chart_xml(sheet: &Sheet, chart: &SheetChart, exported_sheet_name: &str) -> String {
    let start_row = chart.start_row + 1;
    let end_row = chart.end_row.map(|row| row + 1).unwrap_or_else(|| {
        sheet
            .used_range()
            .map(|(_, _, _, max_row)| max_row + 1)
            .unwrap_or(2)
            .max(2)
    });
    let name = chart_sheet_reference(exported_sheet_name);
    let cat_column = column_letters(chart.cat_col as usize);
    let val_column = column_letters(chart.val_col as usize);
    // Spreadsheet quoting and XML escaping are separate operations. The
    // sheet name is quoted for the formula grammar above; escape the complete
    // generated formula before putting it in element text.
    let cat_range = xml_escape_text(&format!(
        "{name}!${cat_column}${start_row}:${cat_column}${end_row}"
    ));
    let val_range = xml_escape_text(&format!(
        "{name}!${val_column}${start_row}:${val_column}${end_row}"
    ));
    let title = xml_escape_text(&chart.title);
    let series = match chart.kind {
        ChartKind::Scatter => format!(
            "<c:scatterChart><c:scatterStyle val=\"lineMarker\"/><c:varyColors val=\"0\"/><c:ser><c:idx val=\"0\"/><c:order val=\"0\"/><c:xVal><c:numRef><c:f>{cat_range}</c:f></c:numRef></c:xVal><c:yVal><c:numRef><c:f>{val_range}</c:f></c:numRef></c:yVal></c:ser><c:axId val=\"-2128941756\"/><c:axId val=\"-2128941755\"/></c:scatterChart>"
        ),
        ChartKind::Pie => format!(
            "<c:pieChart><c:varyColors val=\"1\"/><c:ser><c:idx val=\"0\"/><c:order val=\"0\"/><c:cat><c:strRef><c:f>{cat_range}</c:f></c:strRef></c:cat><c:val><c:numRef><c:f>{val_range}</c:f></c:numRef></c:val></c:ser></c:pieChart>"
        ),
        ChartKind::Line => format!(
            "<c:lineChart><c:grouping val=\"standard\"/><c:varyColors val=\"0\"/><c:ser><c:idx val=\"0\"/><c:order val=\"0\"/><c:cat><c:strRef><c:f>{cat_range}</c:f></c:strRef></c:cat><c:val><c:numRef><c:f>{val_range}</c:f></c:numRef></c:val></c:ser><c:axId val=\"-2128941756\"/><c:axId val=\"-2128941755\"/></c:lineChart>"
        ),
        ChartKind::Bar => format!(
            "<c:barChart><c:barDir val=\"col\"/><c:grouping val=\"clustered\"/><c:varyColors val=\"0\"/><c:ser><c:idx val=\"0\"/><c:order val=\"0\"/><c:cat><c:strRef><c:f>{cat_range}</c:f></c:strRef></c:cat><c:val><c:numRef><c:f>{val_range}</c:f></c:numRef></c:val></c:ser><c:axId val=\"-2128941756\"/><c:axId val=\"-2128941755\"/></c:barChart>"
        ),
    };
    let axes = match chart.kind {
        ChartKind::Bar | ChartKind::Line => "<c:catAx><c:axId val=\"-2128941756\"/><c:scaling><c:orientation val=\"minMax\"/></c:scaling><c:delete val=\"0\"/><c:axPos val=\"b\"/><c:crossAx val=\"-2128941755\"/><c:crosses val=\"autoZero\"/><c:auto val=\"1\"/><c:lblAlgn val=\"ctr\"/><c:lblOffset val=\"100\"/></c:catAx><c:valAx><c:axId val=\"-2128941755\"/><c:scaling><c:orientation val=\"minMax\"/></c:scaling><c:delete val=\"0\"/><c:axPos val=\"l\"/><c:crossAx val=\"-2128941756\"/><c:crosses val=\"autoZero\"/><c:crossBetween val=\"midCat\"/></c:valAx>",
        ChartKind::Scatter => "<c:valAx><c:axId val=\"-2128941756\"/><c:scaling><c:orientation val=\"minMax\"/></c:scaling><c:delete val=\"0\"/><c:axPos val=\"b\"/><c:crossAx val=\"-2128941755\"/><c:crosses val=\"autoZero\"/></c:valAx><c:valAx><c:axId val=\"-2128941755\"/><c:scaling><c:orientation val=\"minMax\"/></c:scaling><c:delete val=\"0\"/><c:axPos val=\"l\"/><c:crossAx val=\"-2128941756\"/><c:crosses val=\"autoZero\"/></c:valAx>",
        ChartKind::Pie => "",
    };
    format!(
        "<?xml version=\"1.0\"?><c:chartSpace xmlns:c=\"{CHART_NS}\" xmlns:a=\"{DRAWINGML_NS}\"><c:chart><c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang=\"en-US\"/><a:t>{title}</a:t></a:r></a:p></c:rich></c:tx><c:layout/></c:title><c:plotArea><c:layout/>{series}{axes}</c:plotArea><c:plotVisOnly val=\"1\"/></c:chart></c:chartSpace>"
    )
}

fn worksheet_drawing_rels(drawing_number: usize) -> String {
    format!(
        "<?xml version=\"1.0\"?><Relationships xmlns=\"{PACKAGE_REL_NS}\"><Relationship Id=\"rId1\" Type=\"{DRAWING_REL_TYPE}\" Target=\"../drawings/drawing{drawing_number}.xml\"/></Relationships>"
    )
}

fn render_content_types(
    base: &str,
    sheets: &[Sheet],
    image_extensions: &BTreeSet<String>,
) -> String {
    let mut additions = String::new();
    additions.push_str(
        "<Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/>",
    );
    for (index, sheet) in sheets.iter().enumerate() {
        if sheet.chart.is_some() || !sheet.objects.is_empty() {
            additions.push_str(&format!(
                "<Override PartName=\"/xl/drawings/drawing{}.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.drawing+xml\"/>",
                index + 1
            ));
        }
        if sheet.chart.is_some() {
            additions.push_str(&format!(
                "<Override PartName=\"/xl/charts/chart{}.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.drawingml.chart+xml\"/>",
                index + 1
            ));
        }
    }
    for extension in image_extensions {
        let mime = match extension.as_str() {
            "jpg" | "jpeg" => "image/jpeg",
            "gif" => "image/gif",
            "webp" => "image/webp",
            "svg" => "image/svg+xml",
            _ => "image/png",
        };
        additions.push_str(&format!(
            "<Default Extension=\"{extension}\" ContentType=\"{mime}\"/>"
        ));
    }
    base.replace("</Types>", &format!("{additions}</Types>"))
}

const DRAWING_REL_TYPE: &str =
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing";
const CHART_REL_TYPE: &str =
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart";
const IMAGE_REL_TYPE: &str =
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image";
const CHART_GRAPHIC_URI: &str = "http://schemas.openxmlformats.org/drawingml/2006/chart";

fn image_extension_for_object(object: &SheetObject) -> &'static str {
    let source = if object.path.trim().is_empty() {
        object.asset.as_deref().unwrap_or("image.png")
    } else {
        &object.path
    };
    match source
        .rsplit('.')
        .next()
        .unwrap_or("png")
        .to_ascii_lowercase()
        .as_str()
    {
        "jpg" | "jpeg" => "jpg",
        "gif" => "gif",
        "webp" => "webp",
        "svg" | "svgz" => "svg",
        _ => "png",
    }
}
