//! Production services shared by every Loom application.
//!
//! The crate deliberately contains no UI or application-model dependency. It
//! provides durable operation journals, atomic checkpoints, localization
//! fallback, deterministic performance summaries, accessibility auditing, and
//! release-target validation that can be adopted by Writer, Sheets, Present,
//! Photo, Motion, Video, Studio, and Encode.

#![forbid(unsafe_code)]

/// Deduplicating full-state recovery coordination for Loom applications.
pub mod snapshot;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File, OpenOptions};
use std::io::{self, BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

const JOURNAL_FILE: &str = "operations.jsonl";
const CHECKPOINT_FILE: &str = "checkpoint.bin";
const CHECKPOINT_META_FILE: &str = "checkpoint.json";
const CHECKPOINT_GENERATION_PREFIX: &str = "checkpoint-generation-";
const CHECKPOINT_GENERATION_PAYLOAD_SUFFIX: &str = ".bin";
const CHECKPOINT_GENERATION_METADATA_SUFFIX: &str = ".json";
const CHECKPOINT_COMMIT_PREFIX: &str = "checkpoint-commit-";
const CHECKPOINT_COMMIT_SUFFIX: &str = ".json";

/// The pointer is the one-file commit record for a checkpoint generation.
///
/// The generation payload and metadata are written and verified before this
/// record is published. Older installations wrote [`CheckpointMetadata`]
/// directly to `checkpoint.json`; recovery still accepts that legacy shape.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct CheckpointPointer {
    generation: u64,
    last_sequence: u64,
    sha256: String,
    timestamp_ms: u128,
    schema: String,
}

impl CheckpointPointer {
    fn metadata(&self) -> CheckpointMetadata {
        CheckpointMetadata {
            last_sequence: self.last_sequence,
            sha256: self.sha256.clone(),
            timestamp_ms: self.timestamp_ms,
            schema: self.schema.clone(),
        }
    }
}

/// Error returned by production-service operations.
#[derive(Debug)]
pub enum ProductionError {
    /// Filesystem failure.
    Io(io::Error),
    /// Invalid serialized state.
    InvalidData(String),
    /// Integrity verification failed.
    Integrity(String),
    /// A synchronization primitive was poisoned.
    Poisoned,
}

impl std::fmt::Display for ProductionError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(error) => write!(formatter, "I/O error: {error}"),
            Self::InvalidData(message) => write!(formatter, "invalid data: {message}"),
            Self::Integrity(message) => write!(formatter, "integrity failure: {message}"),
            Self::Poisoned => write!(formatter, "shared state is poisoned"),
        }
    }
}

impl std::error::Error for ProductionError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(error) => Some(error),
            _ => None,
        }
    }
}

impl From<io::Error> for ProductionError {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

/// One durable, replayable application operation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct JournalRecord {
    /// Monotonically increasing sequence number.
    pub sequence: u64,
    /// Stable operation identifier, normally a UUID generated by the app.
    pub operation_id: String,
    /// Human-readable operation label used by recovery UI.
    pub label: String,
    /// Application-owned serialized command or mutation payload.
    pub payload: Vec<u8>,
    /// Unix timestamp in milliseconds.
    pub timestamp_ms: u128,
    /// Lowercase SHA-256 of the payload.
    pub payload_sha256: String,
}

impl JournalRecord {
    fn verify(&self) -> Result<(), ProductionError> {
        let actual = sha256_hex(&self.payload);
        if actual != self.payload_sha256 {
            return Err(ProductionError::Integrity(format!(
                "operation {} payload digest mismatch",
                self.operation_id
            )));
        }
        Ok(())
    }
}

/// Metadata for the last atomic checkpoint.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CheckpointMetadata {
    /// Last journal sequence represented by the checkpoint.
    pub last_sequence: u64,
    /// SHA-256 of the checkpoint bytes.
    pub sha256: String,
    /// Unix timestamp in milliseconds.
    pub timestamp_ms: u128,
    /// Application schema identifier.
    pub schema: String,
}

/// Recovered checkpoint plus operations that must be replayed after it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RecoveryState {
    /// Last valid checkpoint bytes, when available.
    pub checkpoint: Option<Vec<u8>>,
    /// Checkpoint metadata, when available.
    pub checkpoint_metadata: Option<CheckpointMetadata>,
    /// Verified operations newer than the checkpoint.
    pub operations: Vec<JournalRecord>,
}

/// Crash-safe append-only operation journal with atomic checkpoints.
///
/// A journal write is flushed with `sync_data` before [`append`](Self::append)
/// returns. Checkpoints are written to sibling temporary files, synced, and
/// atomically renamed. Corrupt records are rejected rather than silently
/// replayed.
#[derive(Debug)]
pub struct RecoveryJournal {
    directory: PathBuf,
    next_sequence: u64,
}

impl RecoveryJournal {
    /// Open or create a journal directory and validate all existing records.
    ///
    /// A crash that interrupted an append can leave a torn final line that
    /// was never durably synced. Open tolerates exactly that case: the
    /// verified prefix is kept, the torn tail is dropped, and the journal is
    /// repaired in place so later appends cannot resurrect the torn line.
    /// Any other damage (interior corruption, broken checksums, non-monotonic
    /// sequences) still fails loudly.
    pub fn open(directory: impl AsRef<Path>) -> Result<Self, ProductionError> {
        let directory = directory.as_ref().to_path_buf();
        fs::create_dir_all(&directory)?;
        let read = read_records_at(&directory.join(JOURNAL_FILE), true)?;
        if read.skipped_tail {
            repair_journal(&directory, &read.records)?;
        }
        let journal_sequence = read.records.last().map(|record| record.sequence);
        let checkpoint_sequence = read_checkpoint_sequence(&directory)?;
        let highest_sequence = journal_sequence
            .into_iter()
            .chain(checkpoint_sequence)
            .max();
        let next_sequence = match highest_sequence {
            Some(sequence) => checked_next_sequence(sequence)?,
            None => 1,
        };
        Ok(Self {
            directory,
            next_sequence,
        })
    }

    /// Journal root directory.
    pub fn directory(&self) -> &Path {
        &self.directory
    }

    /// Append one operation and durably flush it before returning.
    pub fn append(
        &mut self,
        operation_id: impl Into<String>,
        label: impl Into<String>,
        payload: Vec<u8>,
    ) -> Result<JournalRecord, ProductionError> {
        let next_sequence = checked_next_sequence(self.next_sequence)?;
        let record = JournalRecord {
            sequence: self.next_sequence,
            operation_id: operation_id.into(),
            label: label.into(),
            payload_sha256: sha256_hex(&payload),
            payload,
            timestamp_ms: unix_time_ms(),
        };
        record.verify()?;
        let encoded = serde_json::to_vec(&record)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        let path = self.directory.join(JOURNAL_FILE);
        let mut file = OpenOptions::new().create(true).append(true).open(path)?;
        file.write_all(&encoded)?;
        file.write_all(b"\n")?;
        file.flush()?;
        file.sync_data()?;
        self.next_sequence = next_sequence;
        Ok(record)
    }

    /// Return every verified journal record.
    pub fn records(&self) -> Result<Vec<JournalRecord>, ProductionError> {
        read_records(&self.directory.join(JOURNAL_FILE))
    }

    /// Atomically write an application checkpoint.
    pub fn checkpoint(
        &self,
        last_sequence: u64,
        schema: impl Into<String>,
        bytes: &[u8],
    ) -> Result<CheckpointMetadata, ProductionError> {
        let metadata = CheckpointMetadata {
            last_sequence,
            sha256: sha256_hex(bytes),
            timestamp_ms: unix_time_ms(),
            schema: schema.into(),
        };
        let metadata_bytes = serde_json::to_vec_pretty(&metadata)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        let generation = next_checkpoint_generation(&self.directory)?;
        let payload_path = checkpoint_generation_payload_path(&self.directory, generation);
        let metadata_path = checkpoint_generation_metadata_path(&self.directory, generation);

        // A generation is complete before its pointer is published. A failure
        // in either write leaves the previous pointer and journal untouched.
        atomic_write(&payload_path, bytes)?;
        atomic_write(&metadata_path, &metadata_bytes)?;
        let (verified_bytes, verified_metadata) =
            read_checkpoint_generation(&self.directory, generation)?;
        if verified_bytes != bytes || verified_metadata != metadata {
            return Err(ProductionError::Integrity(
                "checkpoint generation changed before publication".into(),
            ));
        }

        let pointer = CheckpointPointer {
            generation,
            last_sequence,
            sha256: metadata.sha256.clone(),
            timestamp_ms: metadata.timestamp_ms,
            schema: metadata.schema.clone(),
        };
        let pointer_bytes = serde_json::to_vec_pretty(&pointer)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        publish_checkpoint_pointer(&self.directory, generation, &pointer_bytes)?;
        Ok(metadata)
    }

    /// Load the last valid checkpoint and all operations after it.
    pub fn recover(&self) -> Result<RecoveryState, ProductionError> {
        let (checkpoint, checkpoint_metadata) = read_checkpoint(&self.directory)?;
        let last_sequence = checkpoint_metadata
            .as_ref()
            .map_or(0, |metadata| metadata.last_sequence);
        let operations = self
            .records()?
            .into_iter()
            .filter(|record| record.sequence > last_sequence)
            .collect();
        Ok(RecoveryState {
            checkpoint,
            checkpoint_metadata,
            operations,
        })
    }

    /// Compact the journal by retaining only records newer than `sequence`.
    pub fn compact(&self, sequence: u64) -> Result<(), ProductionError> {
        let records: Vec<JournalRecord> = self
            .records()?
            .into_iter()
            .filter(|record| record.sequence > sequence)
            .collect();
        let mut encoded = Vec::new();
        for record in records {
            serde_json::to_writer(&mut encoded, &record)
                .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
            encoded.push(b'\n');
        }
        atomic_write(&self.directory.join(JOURNAL_FILE), &encoded)
    }
}

/// Outcome of reading a journal, including whether a torn tail was dropped.
struct JournalRead {
    records: Vec<JournalRecord>,
    skipped_tail: bool,
}

fn checked_next_sequence(sequence: u64) -> Result<u64, ProductionError> {
    sequence.checked_add(1).ok_or_else(|| {
        ProductionError::Integrity("journal sequence is exhausted at u64::MAX".into())
    })
}

fn read_checkpoint_sequence(directory: &Path) -> Result<Option<u64>, ProductionError> {
    #[cfg(windows)]
    if let Some(pointer) = read_latest_commit_pointer(directory)? {
        return Ok(Some(pointer.last_sequence));
    }

    let metadata_path = directory.join(CHECKPOINT_META_FILE);
    if metadata_path.exists() {
        let raw = fs::read(metadata_path)?;
        let value: serde_json::Value = serde_json::from_slice(&raw).map_err(|error| {
            ProductionError::InvalidData(format!("checkpoint metadata is not valid JSON: {error}"))
        })?;
        if value.get("generation").is_some() {
            let pointer: CheckpointPointer = serde_json::from_value(value).map_err(|error| {
                ProductionError::InvalidData(format!("checkpoint pointer is invalid: {error}"))
            })?;
            return Ok(Some(pointer.last_sequence));
        }
        let metadata: CheckpointMetadata = serde_json::from_value(value).map_err(|error| {
            ProductionError::InvalidData(format!("checkpoint metadata is invalid: {error}"))
        })?;
        return Ok(Some(metadata.last_sequence));
    }

    Ok(None)
}

fn read_checkpoint(
    directory: &Path,
) -> Result<(Option<Vec<u8>>, Option<CheckpointMetadata>), ProductionError> {
    #[cfg(windows)]
    if let Some(pointer) = read_latest_commit_pointer(directory)? {
        let (bytes, metadata) = read_checkpoint_generation(directory, pointer.generation)?;
        if metadata != pointer.metadata() {
            return Err(ProductionError::Integrity(format!(
                "checkpoint generation {} does not match its commit record",
                pointer.generation
            )));
        }
        return Ok((Some(bytes), Some(metadata)));
    }

    let metadata_path = directory.join(CHECKPOINT_META_FILE);
    let checkpoint_path = directory.join(CHECKPOINT_FILE);
    if !metadata_path.exists() {
        if checkpoint_path.exists() {
            return Err(ProductionError::Integrity(
                "checkpoint metadata and payload must both exist".into(),
            ));
        }
        return Ok((None, None));
    }

    let raw = fs::read(&metadata_path)?;
    let value: serde_json::Value = serde_json::from_slice(&raw).map_err(|error| {
        ProductionError::InvalidData(format!("checkpoint metadata is not valid JSON: {error}"))
    })?;
    if value.get("generation").is_some() {
        let pointer: CheckpointPointer = serde_json::from_value(value).map_err(|error| {
            ProductionError::InvalidData(format!("checkpoint pointer is invalid: {error}"))
        })?;
        let (bytes, metadata) = read_checkpoint_generation(directory, pointer.generation)?;
        if metadata != pointer.metadata() {
            return Err(ProductionError::Integrity(format!(
                "checkpoint generation {} does not match its commit record",
                pointer.generation
            )));
        }
        return Ok((Some(bytes), Some(metadata)));
    }

    if !checkpoint_path.exists() {
        return Err(ProductionError::Integrity(
            "checkpoint metadata and payload must both exist".into(),
        ));
    }

    // Legacy format: checkpoint.json and checkpoint.bin were replaced
    // independently. It remains readable for existing installations; all new
    // checkpoints use a generation pair and a single commit pointer.
    let metadata: CheckpointMetadata = serde_json::from_value(value).map_err(|error| {
        ProductionError::InvalidData(format!("checkpoint metadata is invalid: {error}"))
    })?;
    let bytes = fs::read(checkpoint_path)?;
    if sha256_hex(&bytes) != metadata.sha256 {
        return Err(ProductionError::Integrity(
            "checkpoint digest mismatch".into(),
        ));
    }
    Ok((Some(bytes), Some(metadata)))
}

fn checkpoint_generation_payload_path(directory: &Path, generation: u64) -> PathBuf {
    directory.join(format!(
        "{CHECKPOINT_GENERATION_PREFIX}{generation}{CHECKPOINT_GENERATION_PAYLOAD_SUFFIX}"
    ))
}

fn checkpoint_generation_metadata_path(directory: &Path, generation: u64) -> PathBuf {
    directory.join(format!(
        "{CHECKPOINT_GENERATION_PREFIX}{generation}{CHECKPOINT_GENERATION_METADATA_SUFFIX}"
    ))
}

#[cfg(windows)]
fn checkpoint_commit_path(directory: &Path, generation: u64) -> PathBuf {
    directory.join(format!(
        "{CHECKPOINT_COMMIT_PREFIX}{generation}{CHECKPOINT_COMMIT_SUFFIX}"
    ))
}

fn parse_checkpoint_generation(name: &str, prefix: &str, suffix: &str) -> Option<u64> {
    name.strip_prefix(prefix)
        .and_then(|name| name.strip_suffix(suffix))
        .and_then(|id| id.parse().ok())
}

fn next_checkpoint_generation(directory: &Path) -> Result<u64, ProductionError> {
    let mut highest = 0;
    if directory.exists() {
        for entry in fs::read_dir(directory)? {
            let name = entry?.file_name();
            let Some(name) = name.to_str() else {
                continue;
            };
            let generation = parse_checkpoint_generation(
                name,
                CHECKPOINT_GENERATION_PREFIX,
                CHECKPOINT_GENERATION_PAYLOAD_SUFFIX,
            )
            .or_else(|| {
                parse_checkpoint_generation(
                    name,
                    CHECKPOINT_GENERATION_PREFIX,
                    CHECKPOINT_GENERATION_METADATA_SUFFIX,
                )
            })
            .or_else(|| {
                parse_checkpoint_generation(
                    name,
                    CHECKPOINT_COMMIT_PREFIX,
                    CHECKPOINT_COMMIT_SUFFIX,
                )
            });
            if let Some(generation) = generation {
                highest = highest.max(generation);
            }
        }
    }
    highest.checked_add(1).ok_or_else(|| {
        ProductionError::Integrity("checkpoint generation is exhausted at u64::MAX".into())
    })
}

fn read_checkpoint_generation(
    directory: &Path,
    generation: u64,
) -> Result<(Vec<u8>, CheckpointMetadata), ProductionError> {
    let payload_path = checkpoint_generation_payload_path(directory, generation);
    let metadata_path = checkpoint_generation_metadata_path(directory, generation);
    if !payload_path.exists() || !metadata_path.exists() {
        return Err(ProductionError::Integrity(format!(
            "checkpoint generation {generation} is incomplete"
        )));
    }
    let raw = fs::read(&metadata_path)?;
    let metadata: CheckpointMetadata = serde_json::from_slice(&raw).map_err(|error| {
        ProductionError::InvalidData(format!(
            "checkpoint generation {generation} metadata is invalid: {error}"
        ))
    })?;
    let bytes = fs::read(&payload_path)?;
    if sha256_hex(&bytes) != metadata.sha256 {
        return Err(ProductionError::Integrity(format!(
            "checkpoint generation {generation} digest mismatch"
        )));
    }
    Ok((bytes, metadata))
}

#[cfg(windows)]
fn read_latest_commit_pointer(
    directory: &Path,
) -> Result<Option<CheckpointPointer>, ProductionError> {
    let mut candidates = Vec::new();
    if !directory.exists() {
        return Ok(None);
    }
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        let Some(generation) =
            parse_checkpoint_generation(name, CHECKPOINT_COMMIT_PREFIX, CHECKPOINT_COMMIT_SUFFIX)
        else {
            continue;
        };
        candidates.push((generation, path));
    }
    candidates.sort_by_key(|(generation, _)| *generation);
    let Some((generation, path)) = candidates.pop() else {
        return Ok(None);
    };
    let pointer: CheckpointPointer = serde_json::from_slice(&fs::read(path)?).map_err(|error| {
        ProductionError::InvalidData(format!(
            "checkpoint commit record {generation} is invalid: {error}"
        ))
    })?;
    if pointer.generation != generation {
        return Err(ProductionError::Integrity(format!(
            "checkpoint commit record {generation} names generation {}",
            pointer.generation
        )));
    }
    Ok(Some(pointer))
}

fn publish_checkpoint_pointer(
    directory: &Path,
    _generation: u64,
    pointer_bytes: &[u8],
) -> Result<(), ProductionError> {
    // A leftover pointer temp means a previous publication did not finish.
    // Keep the existing pointer authoritative until that obstruction is
    // removed; this also makes the legacy temp-file failure mode explicit on
    // platforms that publish through unique commit records.
    let legacy_temporary = directory.join(format!(
        ".{CHECKPOINT_META_FILE}.{}.tmp",
        std::process::id()
    ));
    if legacy_temporary.exists() {
        if legacy_temporary.is_dir() {
            return Err(ProductionError::Io(io::Error::new(
                io::ErrorKind::AlreadyExists,
                format!(
                    "checkpoint pointer temp is blocked: {}",
                    legacy_temporary.display()
                ),
            )));
        }
        fs::remove_file(&legacy_temporary)?;
    }

    #[cfg(windows)]
    {
        // Windows std::fs::rename cannot replace an existing file. A unique,
        // fully synced commit record gives startup the same atomic choice
        // without deleting the previous pointer before publishing this one.
        return atomic_write(
            &checkpoint_commit_path(directory, _generation),
            pointer_bytes,
        );
    }

    #[cfg(not(windows))]
    {
        // On Unix rename replaces the old pointer atomically. The old pointer
        // remains readable until this commit point, and the generation pair
        // has already been verified above.
        atomic_write(&directory.join(CHECKPOINT_META_FILE), pointer_bytes)
    }
}

fn read_records(path: &Path) -> Result<Vec<JournalRecord>, ProductionError> {
    Ok(read_records_at(path, false)?.records)
}

/// Read journal records. When `tolerant_tail` is set, a final line that fails
/// to parse is treated as a torn append tail rather than an error.
fn read_records_at(path: &Path, tolerant_tail: bool) -> Result<JournalRead, ProductionError> {
    if !path.exists() {
        return Ok(JournalRead {
            records: Vec::new(),
            skipped_tail: false,
        });
    }
    let reader = BufReader::new(File::open(path)?);
    let mut raw_lines = Vec::new();
    for line in reader.lines() {
        raw_lines.push(line?);
    }
    let mut records = Vec::new();
    let mut previous = 0;
    let mut skipped_tail = false;
    for (index, line) in raw_lines.iter().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let is_last = index + 1 == raw_lines.len();
        let record: JournalRecord = match serde_json::from_str(line) {
            Ok(record) => record,
            Err(error) => {
                if tolerant_tail && is_last {
                    skipped_tail = true;
                    break;
                }
                return Err(ProductionError::InvalidData(format!(
                    "journal line {}: {error}",
                    index + 1
                )));
            }
        };
        record.verify()?;
        if record.sequence <= previous {
            return Err(ProductionError::Integrity(format!(
                "journal sequence {} is not monotonic",
                record.sequence
            )));
        }
        previous = record.sequence;
        records.push(record);
    }
    Ok(JournalRead {
        records,
        skipped_tail,
    })
}

/// Persist only the verified prefix of a journal, dropping a torn tail so a
/// later crash cannot make it appear interior to valid records.
fn repair_journal(directory: &Path, records: &[JournalRecord]) -> Result<(), ProductionError> {
    let mut encoded = Vec::new();
    for record in records {
        serde_json::to_writer(&mut encoded, record)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        encoded.push(b'\n');
    }
    atomic_write(&directory.join(JOURNAL_FILE), &encoded)
}

fn atomic_write(path: &Path, bytes: &[u8]) -> Result<(), ProductionError> {
    let parent = path
        .parent()
        .ok_or_else(|| ProductionError::InvalidData("path has no parent".into()))?;
    fs::create_dir_all(parent)?;
    let temporary = parent.join(format!(
        ".{}.{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("loom"),
        std::process::id()
    ));
    let write_result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)?;
        file.write_all(bytes)?;
        file.flush()?;
        file.sync_all()?;
        Ok::<(), io::Error>(())
    })();
    if let Err(error) = write_result {
        let _ = fs::remove_file(&temporary);
        return Err(error.into());
    }

    // Unix rename replaces the destination atomically. Windows does not
    // expose that operation through std::fs; checkpoint publication therefore
    // uses unique commit records there and never calls this branch for an
    // existing checkpoint pointer.
    #[cfg(windows)]
    if path.exists() {
        fs::remove_file(path)?;
    }
    if let Err(error) = fs::rename(&temporary, path) {
        let _ = fs::remove_file(&temporary);
        return Err(error.into());
    }
    sync_directory(parent)?;
    Ok(())
}

#[cfg(unix)]
fn sync_directory(path: &Path) -> Result<(), ProductionError> {
    File::open(path)?.sync_all()?;
    Ok(())
}

#[cfg(not(unix))]
fn sync_directory(_path: &Path) -> Result<(), ProductionError> {
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut output = String::with_capacity(64);
    for byte in digest {
        use std::fmt::Write as _;
        let _ = write!(output, "{byte:02x}");
    }
    output
}

fn unix_time_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

/// Runtime-localized message catalogue with deterministic fallback.
#[derive(Debug, Clone, Default)]
pub struct LocaleCatalog {
    default_locale: String,
    messages: BTreeMap<String, BTreeMap<String, String>>,
}

impl LocaleCatalog {
    /// Create a catalogue with the given default locale.
    pub fn new(default_locale: impl Into<String>) -> Self {
        Self {
            default_locale: normalize_locale(&default_locale.into()),
            messages: BTreeMap::new(),
        }
    }

    /// Add or replace one locale from a JSON object of string values.
    pub fn load_json(&mut self, locale: &str, json: &str) -> Result<(), ProductionError> {
        let parsed: BTreeMap<String, String> = serde_json::from_str(json)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        self.messages.insert(normalize_locale(locale), parsed);
        Ok(())
    }

    /// Resolve a message using exact locale, language-only, then default.
    pub fn resolve(&self, locale: &str, key: &str) -> Option<&str> {
        let locale = normalize_locale(locale);
        let language = locale.split('-').next().unwrap_or(&locale);
        for candidate in [locale.as_str(), language, self.default_locale.as_str()] {
            if let Some(value) = self
                .messages
                .get(candidate)
                .and_then(|messages| messages.get(key))
            {
                return Some(value);
            }
        }
        None
    }

    /// Resolve and replace `{name}` placeholders from a deterministic map.
    pub fn format(
        &self,
        locale: &str,
        key: &str,
        arguments: &BTreeMap<String, String>,
    ) -> Option<String> {
        let mut output = self.resolve(locale, key)?.to_string();
        for (name, value) in arguments {
            output = output.replace(&format!("{{{name}}}"), value);
        }
        Some(output)
    }

    /// Locale identifiers currently loaded.
    pub fn locales(&self) -> impl Iterator<Item = &str> {
        self.messages.keys().map(String::as_str)
    }
}

fn normalize_locale(locale: &str) -> String {
    locale.trim().replace('_', "-").to_ascii_lowercase()
}

/// One measured span.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct TraceSample {
    /// Span category, such as `render.preview`.
    pub category: String,
    /// Duration in nanoseconds.
    pub duration_ns: u128,
}

/// Aggregate latency statistics for a category.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct LatencySummary {
    /// Sample count.
    pub count: usize,
    /// Minimum duration.
    pub min: Duration,
    /// Median duration.
    pub p50: Duration,
    /// 95th percentile duration.
    pub p95: Duration,
    /// 99th percentile duration.
    pub p99: Duration,
    /// Maximum duration.
    pub max: Duration,
}

/// Thread-safe in-process trace recorder.
#[derive(Debug, Clone, Default)]
pub struct TraceRecorder {
    samples: Arc<Mutex<Vec<TraceSample>>>,
}

impl TraceRecorder {
    /// Start a span. It is recorded when the returned guard is dropped.
    pub fn span(&self, category: impl Into<String>) -> TraceSpan {
        TraceSpan {
            category: category.into(),
            started: Instant::now(),
            recorder: self.clone(),
        }
    }

    /// Add a pre-measured sample.
    pub fn record(
        &self,
        category: impl Into<String>,
        duration: Duration,
    ) -> Result<(), ProductionError> {
        self.samples
            .lock()
            .map_err(|_| ProductionError::Poisoned)?
            .push(TraceSample {
                category: category.into(),
                duration_ns: duration.as_nanos(),
            });
        Ok(())
    }

    /// Snapshot all current samples.
    pub fn samples(&self) -> Result<Vec<TraceSample>, ProductionError> {
        Ok(self
            .samples
            .lock()
            .map_err(|_| ProductionError::Poisoned)?
            .clone())
    }

    /// Compute latency percentiles for one category.
    pub fn summary(&self, category: &str) -> Result<Option<LatencySummary>, ProductionError> {
        let mut values: Vec<u128> = self
            .samples()?
            .into_iter()
            .filter(|sample| sample.category == category)
            .map(|sample| sample.duration_ns)
            .collect();
        if values.is_empty() {
            return Ok(None);
        }
        values.sort_unstable();
        Ok(Some(LatencySummary {
            count: values.len(),
            min: duration_from_nanos(values[0]),
            p50: duration_from_nanos(percentile(&values, 50)),
            p95: duration_from_nanos(percentile(&values, 95)),
            p99: duration_from_nanos(percentile(&values, 99)),
            max: duration_from_nanos(*values.last().unwrap_or(&values[0])),
        }))
    }

    /// Serialize a deterministic JSON trace snapshot.
    pub fn to_json(&self) -> Result<String, ProductionError> {
        serde_json::to_string_pretty(&self.samples()?)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))
    }
}

/// RAII performance span.
#[derive(Debug)]
pub struct TraceSpan {
    category: String,
    started: Instant,
    recorder: TraceRecorder,
}

impl Drop for TraceSpan {
    fn drop(&mut self) {
        let _ = self
            .recorder
            .record(self.category.clone(), self.started.elapsed());
    }
}

fn percentile(values: &[u128], percentile: usize) -> u128 {
    let index = ((values.len() - 1) * percentile).div_ceil(100);
    values[index.min(values.len() - 1)]
}

fn duration_from_nanos(nanos: u128) -> Duration {
    Duration::from_nanos(nanos.min(u64::MAX as u128) as u64)
}

/// Accessibility metadata for one interactive UI node.
#[derive(Debug, Clone, PartialEq)]
pub struct AccessibilityNode {
    /// Stable accessibility identifier.
    pub id: String,
    /// Semantic role.
    pub role: String,
    /// Spoken label.
    pub label: String,
    /// Optional spoken description.
    pub description: String,
    /// Logical width in device-independent pixels.
    pub width: f32,
    /// Logical height in device-independent pixels.
    pub height: f32,
    /// Foreground relative luminance in the range 0..=1.
    pub foreground_luminance: f32,
    /// Background relative luminance in the range 0..=1.
    pub background_luminance: f32,
    /// Whether keyboard focus can reach the node.
    pub keyboard_focusable: bool,
}

/// Accessibility audit finding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AccessibilityFinding {
    /// Node id, or `document` for global findings.
    pub node_id: String,
    /// Stable rule identifier.
    pub rule: String,
    /// Human-readable failure description.
    pub message: String,
}

/// Audit interactive nodes for baseline WCAG-oriented requirements.
pub fn audit_accessibility(nodes: &[AccessibilityNode]) -> Vec<AccessibilityFinding> {
    let mut findings = Vec::new();
    let mut ids = BTreeSet::new();
    for node in nodes {
        if node.id.trim().is_empty() {
            findings.push(finding(node, "id.required", "interactive node has no id"));
        } else if !ids.insert(node.id.clone()) {
            findings.push(finding(node, "id.unique", "accessibility id is duplicated"));
        }
        if node.role.trim().is_empty() {
            findings.push(finding(node, "role.required", "semantic role is missing"));
        }
        if node.label.trim().is_empty() {
            findings.push(finding(node, "label.required", "spoken label is missing"));
        }
        if node.width < 24.0 || node.height < 24.0 {
            findings.push(finding(
                node,
                "target.minimum",
                "interactive target is smaller than 24 by 24 logical pixels",
            ));
        }
        if !node.keyboard_focusable {
            findings.push(finding(
                node,
                "keyboard.reachable",
                "interactive node cannot receive keyboard focus",
            ));
        }
        let ratio = contrast_ratio(node.foreground_luminance, node.background_luminance);
        if ratio < 4.5 {
            findings.push(finding(
                node,
                "contrast.normal-text",
                &format!("contrast ratio {ratio:.2}:1 is below 4.5:1"),
            ));
        }
    }
    findings
}

fn finding(node: &AccessibilityNode, rule: &str, message: &str) -> AccessibilityFinding {
    AccessibilityFinding {
        node_id: if node.id.is_empty() {
            "document".into()
        } else {
            node.id.clone()
        },
        rule: rule.into(),
        message: message.into(),
    }
}

fn contrast_ratio(first: f32, second: f32) -> f32 {
    let light = first.max(second).clamp(0.0, 1.0);
    let dark = first.min(second).clamp(0.0, 1.0);
    (light + 0.05) / (dark + 0.05)
}

/// Operating-system family supported by a release artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum OperatingSystem {
    /// Linux desktop.
    Linux,
    /// Microsoft Windows.
    Windows,
    /// Apple macOS.
    MacOs,
}

/// CPU architecture supported by a release artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Architecture {
    /// 64-bit x86.
    X86_64,
    /// 64-bit Arm.
    Aarch64,
}

/// One installer or portable-package target.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InstallerTarget {
    /// Operating system.
    pub operating_system: OperatingSystem,
    /// CPU architecture.
    pub architecture: Architecture,
    /// Package kind, such as `appimage`, `deb`, `msi`, or `dmg`.
    pub package_kind: String,
    /// Whether the artifact must be code-signed.
    pub signing_required: bool,
    /// Whether an automatic updater is supported.
    pub updates_supported: bool,
}

/// Validate that a release matrix covers mandatory desktop targets and package
/// invariants. Returns human-readable errors rather than panicking.
pub fn validate_release_matrix(targets: &[InstallerTarget]) -> Vec<String> {
    let mut errors = Vec::new();
    let mut identities = BTreeSet::new();
    for target in targets {
        let identity = (
            target.operating_system,
            target.architecture,
            target.package_kind.to_ascii_lowercase(),
        );
        if !identities.insert(identity) {
            errors.push(format!(
                "duplicate {:?}/{:?}/{} target",
                target.operating_system, target.architecture, target.package_kind
            ));
        }
        if target.package_kind.trim().is_empty() {
            errors.push("package kind must not be empty".into());
        }
        if matches!(
            target.operating_system,
            OperatingSystem::Windows | OperatingSystem::MacOs
        ) && !target.signing_required
        {
            errors.push(format!(
                "{:?} packages must require code signing",
                target.operating_system
            ));
        }
    }
    for required in [
        (OperatingSystem::Linux, Architecture::X86_64),
        (OperatingSystem::Windows, Architecture::X86_64),
        (OperatingSystem::MacOs, Architecture::Aarch64),
    ] {
        if !targets
            .iter()
            .any(|target| (target.operating_system, target.architecture) == required)
        {
            errors.push(format!(
                "missing {:?}/{:?} release target",
                required.0, required.1
            ));
        }
    }
    errors
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn journal_recovers_after_checkpoint_and_rejects_tampering() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Insert", b"first".to_vec())
            .expect("append");
        journal
            .append("two", "Adjust", b"second".to_vec())
            .expect("append");
        journal
            .checkpoint(1, "loom.test/1", b"checkpoint")
            .expect("checkpoint");
        let state = journal.recover().expect("recover");
        assert_eq!(state.checkpoint.as_deref(), Some(b"checkpoint".as_slice()));
        assert_eq!(state.operations.len(), 1);
        assert_eq!(state.operations[0].operation_id, "two");

        let journal_path = temporary.path().join(JOURNAL_FILE);
        let mut bytes = fs::read(&journal_path).expect("read journal");
        let position = bytes
            .iter()
            .position(|byte| *byte == b's')
            .expect("payload byte");
        bytes[position] = b'x';
        fs::write(journal_path, bytes).expect("tamper");
        assert!(RecoveryJournal::open(temporary.path()).is_err());
    }

    #[test]
    fn checkpoint_generation_failure_preserves_previous_checkpoint_and_journal() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"old contents".to_vec())
            .expect("append");
        journal
            .checkpoint(1, "loom.test/1", b"old contents")
            .expect("checkpoint");
        journal
            .append("two", "Edit", b"latest contents".to_vec())
            .expect("append");

        // This is the legacy metadata-temp location. Publishing the new
        // pointer must fail before it can replace the old pointer.
        let blocker = temporary.path().join(format!(
            ".{CHECKPOINT_META_FILE}.{}.tmp",
            std::process::id()
        ));
        fs::create_dir(&blocker).expect("block metadata temp");
        assert!(journal
            .checkpoint(2, "loom.test/1", b"latest contents")
            .is_err());
        fs::remove_dir(&blocker).expect("remove metadata blocker");
        drop(journal);

        let reopened = RecoveryJournal::open(temporary.path()).expect("reopen");
        let state = reopened.recover().expect("recover previous generation");
        assert_eq!(
            state.checkpoint.as_deref(),
            Some(b"old contents".as_slice())
        );
        assert_eq!(state.operations.len(), 1);
        assert_eq!(state.operations[0].payload, b"latest contents");
    }

    #[test]
    fn journal_sequence_starts_after_checkpoint_sequence() {
        let temporary = tempfile::tempdir().expect("tempdir");
        {
            let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
            journal
                .append("one", "Edit", b"saved".to_vec())
                .expect("append");
            journal
                .checkpoint(1, "loom.test/1", b"saved")
                .expect("checkpoint");
        }
        let mut reopened = RecoveryJournal::open(temporary.path()).expect("reopen");
        let record = reopened
            .append("two", "Edit", b"unsaved".to_vec())
            .expect("append after checkpoint");
        assert_eq!(record.sequence, 2);
        assert_eq!(reopened.recover().expect("recover").operations.len(), 1);
    }

    #[test]
    fn journal_sequence_overflow_is_reported() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let metadata = CheckpointMetadata {
            last_sequence: u64::MAX,
            sha256: sha256_hex(b"checkpoint"),
            timestamp_ms: unix_time_ms(),
            schema: "loom.test/1".into(),
        };
        fs::write(
            temporary.path().join(CHECKPOINT_META_FILE),
            serde_json::to_vec(&metadata).expect("metadata"),
        )
        .expect("write metadata");
        fs::write(temporary.path().join(CHECKPOINT_FILE), b"checkpoint").expect("write checkpoint");
        let error = RecoveryJournal::open(temporary.path()).expect_err("overflow must fail");
        assert!(format!("{error}").contains("exhausted"));
    }

    #[test]
    fn crash_during_append_leaves_torn_tail_that_recovers_and_self_heals() {
        let temporary = tempfile::tempdir().expect("tempdir");
        {
            let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
            for sequence in 1..=3 {
                journal
                    .append("op", "Edit", format!("payload-{sequence}").into_bytes())
                    .expect("append");
            }
            // Simulate a crash interrupting a fourth append: a torn line that
            // was never synced to disk.
            let journal_path = temporary.path().join(JOURNAL_FILE);
            let mut file = OpenOptions::new()
                .append(true)
                .open(&journal_path)
                .expect("open journal");
            file.write_all(b"{\"sequence\": 4,").expect("torn write");
            file.sync_data().expect("sync torn tail");
        }
        // New process: open must tolerate the torn tail and repair the file.
        let mut journal = RecoveryJournal::open(temporary.path()).expect("reopen after crash");
        assert_eq!(journal.records().expect("records").len(), 3);
        let state = journal.recover().expect("recover");
        assert_eq!(state.operations.len(), 3);
        assert_eq!(state.operations[2].payload.as_slice(), b"payload-3");
        // Appending after repair writes a clean record 4.
        journal
            .append("op", "Edit", b"payload-4".to_vec())
            .expect("append after repair");
        let journal_path = temporary.path().join(JOURNAL_FILE);
        let final_lines = fs::read_to_string(journal_path).expect("read repaired journal");
        assert_eq!(final_lines.lines().count(), 4);
        assert!(journal.records().expect("records").len() == 4);
        let reopened = RecoveryJournal::open(temporary.path()).expect("final reopen");
        assert_eq!(
            reopened.records().expect("records")[3].payload.as_slice(),
            b"payload-4"
        );
    }

    #[test]
    fn corrupt_checkpoint_fails_bounded_without_panicking() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"first".to_vec())
            .expect("append");
        journal
            .checkpoint(1, "loom.test/1", b"checkpoint")
            .expect("checkpoint");
        // Garbage checkpoint metadata (non-parseable) must surface as a
        // bounded InvalidData/Integrity error, never a panic.
        fs::write(
            temporary.path().join(CHECKPOINT_META_FILE),
            b"{\"not\": \"json\"\"",
        )
        .expect("corrupt metadata");
        let outcome = journal.recover();
        let error = match &outcome {
            Err(error) => format!("{error}"),
            Ok(_) => panic!("corrupt checkpoint metadata must not recover"),
        };
        assert!(
            error.contains("checkpoint") || error.to_lowercase().contains("json"),
            "error should describe the damaged checkpoint: {error}"
        );
        // Torn checkpoint payload (metadata present, payload garbage) must
        // also be a bounded integrity failure.
        fs::write(temporary.path().join(CHECKPOINT_META_FILE), {
            let metadata = CheckpointMetadata {
                last_sequence: 1,
                sha256: sha256_hex(b"checkpoint"),
                timestamp_ms: unix_time_ms(),
                schema: "loom.test/1".into(),
            };
            serde_json::to_vec_pretty(&metadata).expect("encode metadata")
        })
        .expect("restore metadata");
        fs::write(temporary.path().join(CHECKPOINT_FILE), b"garbage").expect("torn payload");
        let outcome = journal.recover();
        assert!(
            matches!(outcome, Err(ProductionError::Integrity(_))),
            "torn checkpoint payload must be a bounded integrity error"
        );
    }

    #[test]
    fn locale_fallback_and_arguments_are_deterministic() {
        let mut catalog = LocaleCatalog::new("en");
        catalog
            .load_json("en", r#"{"save":"Save {name}","open":"Open"}"#)
            .expect("English");
        catalog
            .load_json("fr", r#"{"open":"Ouvrir"}"#)
            .expect("French");
        assert_eq!(catalog.resolve("fr-CA", "open"), Some("Ouvrir"));
        assert_eq!(catalog.resolve("fr-CA", "save"), Some("Save {name}"));
        let arguments = BTreeMap::from([("name".into(), "Project".into())]);
        assert_eq!(
            catalog.format("fr-CA", "save", &arguments).as_deref(),
            Some("Save Project")
        );
    }

    #[test]
    fn profiler_computes_percentiles() {
        let recorder = TraceRecorder::default();
        for milliseconds in 1..=100 {
            recorder
                .record("preview", Duration::from_millis(milliseconds))
                .expect("record");
        }
        let summary = recorder.summary("preview").expect("summary").expect("data");
        assert_eq!(summary.count, 100);
        assert_eq!(summary.p50, Duration::from_millis(51));
        assert_eq!(summary.p95, Duration::from_millis(96));
        assert_eq!(summary.p99, Duration::from_millis(100));
    }

    #[test]
    fn accessibility_audit_reports_actionable_rules() {
        let node = AccessibilityNode {
            id: "save".into(),
            role: "button".into(),
            label: "".into(),
            description: String::new(),
            width: 18.0,
            height: 18.0,
            foreground_luminance: 0.4,
            background_luminance: 0.5,
            keyboard_focusable: false,
        };
        let rules: BTreeSet<String> = audit_accessibility(&[node])
            .into_iter()
            .map(|finding| finding.rule)
            .collect();
        assert!(rules.contains("label.required"));
        assert!(rules.contains("target.minimum"));
        assert!(rules.contains("keyboard.reachable"));
        assert!(rules.contains("contrast.normal-text"));
    }

    #[test]
    fn release_matrix_requires_all_primary_platforms() {
        let errors = validate_release_matrix(&[InstallerTarget {
            operating_system: OperatingSystem::Linux,
            architecture: Architecture::X86_64,
            package_kind: "appimage".into(),
            signing_required: false,
            updates_supported: true,
        }]);
        assert_eq!(errors.len(), 2);
    }
}
