//! Production services shared by every Loom application.
//!
//! The crate deliberately contains no UI or application-model dependency. It
//! provides durable operation journals, atomic checkpoints, localization
//! fallback, deterministic performance summaries, accessibility auditing, and
//! release-target validation that can be adopted by Writer, Sheets, Present,
//! Photo, Motion, Video, Studio, and Encode.

#![forbid(unsafe_code)]

/// Deduplicating full-state recovery coordination for Loom applications.
pub mod snapshot;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File, OpenOptions};
use std::io::{self, BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

const JOURNAL_FILE: &str = "operations.jsonl";
const CHECKPOINT_FILE: &str = "checkpoint.bin";
const CHECKPOINT_META_FILE: &str = "checkpoint.json";

/// Error returned by production-service operations.
#[derive(Debug)]
pub enum ProductionError {
    /// Filesystem failure.
    Io(io::Error),
    /// Invalid serialized state.
    InvalidData(String),
    /// Integrity verification failed.
    Integrity(String),
    /// A synchronization primitive was poisoned.
    Poisoned,
}

impl std::fmt::Display for ProductionError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(error) => write!(formatter, "I/O error: {error}"),
            Self::InvalidData(message) => write!(formatter, "invalid data: {message}"),
            Self::Integrity(message) => write!(formatter, "integrity failure: {message}"),
            Self::Poisoned => write!(formatter, "shared state is poisoned"),
        }
    }
}

impl std::error::Error for ProductionError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(error) => Some(error),
            _ => None,
        }
    }
}

impl From<io::Error> for ProductionError {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

/// One durable, replayable application operation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct JournalRecord {
    /// Monotonically increasing sequence number.
    pub sequence: u64,
    /// Stable operation identifier, normally a UUID generated by the app.
    pub operation_id: String,
    /// Human-readable operation label used by recovery UI.
    pub label: String,
    /// Application-owned serialized command or mutation payload.
    pub payload: Vec<u8>,
    /// Unix timestamp in milliseconds.
    pub timestamp_ms: u128,
    /// Lowercase SHA-256 of the payload.
    pub payload_sha256: String,
}

impl JournalRecord {
    fn verify(&self) -> Result<(), ProductionError> {
        let actual = sha256_hex(&self.payload);
        if actual != self.payload_sha256 {
            return Err(ProductionError::Integrity(format!(
                "operation {} payload digest mismatch",
                self.operation_id
            )));
        }
        Ok(())
    }
}

/// Metadata for the last atomic checkpoint.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CheckpointMetadata {
    /// Last journal sequence represented by the checkpoint.
    pub last_sequence: u64,
    /// SHA-256 of the checkpoint bytes.
    pub sha256: String,
    /// Unix timestamp in milliseconds.
    pub timestamp_ms: u128,
    /// Application schema identifier.
    pub schema: String,
}

/// Recovered checkpoint plus operations that must be replayed after it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RecoveryState {
    /// Last valid checkpoint bytes, when available.
    pub checkpoint: Option<Vec<u8>>,
    /// Checkpoint metadata, when available.
    pub checkpoint_metadata: Option<CheckpointMetadata>,
    /// Verified operations newer than the checkpoint.
    pub operations: Vec<JournalRecord>,
}

/// Crash-safe append-only operation journal with atomic checkpoints.
///
/// A journal write is flushed with `sync_data` before [`append`](Self::append)
/// returns. Checkpoints are written to sibling temporary files, synced, and
/// atomically renamed. Corrupt records are rejected rather than silently
/// replayed.
#[derive(Debug)]
pub struct RecoveryJournal {
    directory: PathBuf,
    next_sequence: u64,
}

impl RecoveryJournal {
    /// Open or create a journal directory and validate all existing records.
    pub fn open(directory: impl AsRef<Path>) -> Result<Self, ProductionError> {
        let directory = directory.as_ref().to_path_buf();
        fs::create_dir_all(&directory)?;
        let records = read_records(&directory.join(JOURNAL_FILE))?;
        let next_sequence = records
            .last()
            .map_or(1, |record| record.sequence.saturating_add(1));
        Ok(Self {
            directory,
            next_sequence,
        })
    }

    /// Journal root directory.
    pub fn directory(&self) -> &Path {
        &self.directory
    }

    /// Append one operation and durably flush it before returning.
    pub fn append(
        &mut self,
        operation_id: impl Into<String>,
        label: impl Into<String>,
        payload: Vec<u8>,
    ) -> Result<JournalRecord, ProductionError> {
        let record = JournalRecord {
            sequence: self.next_sequence,
            operation_id: operation_id.into(),
            label: label.into(),
            payload_sha256: sha256_hex(&payload),
            payload,
            timestamp_ms: unix_time_ms(),
        };
        record.verify()?;
        let encoded = serde_json::to_vec(&record)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        let path = self.directory.join(JOURNAL_FILE);
        let mut file = OpenOptions::new().create(true).append(true).open(path)?;
        file.write_all(&encoded)?;
        file.write_all(b"\n")?;
        file.flush()?;
        file.sync_data()?;
        self.next_sequence = self.next_sequence.saturating_add(1);
        Ok(record)
    }

    /// Return every verified journal record.
    pub fn records(&self) -> Result<Vec<JournalRecord>, ProductionError> {
        read_records(&self.directory.join(JOURNAL_FILE))
    }

    /// Atomically write an application checkpoint.
    pub fn checkpoint(
        &self,
        last_sequence: u64,
        schema: impl Into<String>,
        bytes: &[u8],
    ) -> Result<CheckpointMetadata, ProductionError> {
        let metadata = CheckpointMetadata {
            last_sequence,
            sha256: sha256_hex(bytes),
            timestamp_ms: unix_time_ms(),
            schema: schema.into(),
        };
        let metadata_bytes = serde_json::to_vec_pretty(&metadata)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        atomic_write(&self.directory.join(CHECKPOINT_FILE), bytes)?;
        atomic_write(&self.directory.join(CHECKPOINT_META_FILE), &metadata_bytes)?;
        Ok(metadata)
    }

    /// Load the last valid checkpoint and all operations after it.
    pub fn recover(&self) -> Result<RecoveryState, ProductionError> {
        let metadata_path = self.directory.join(CHECKPOINT_META_FILE);
        let checkpoint_path = self.directory.join(CHECKPOINT_FILE);
        let (checkpoint, checkpoint_metadata) = if metadata_path.exists()
            || checkpoint_path.exists()
        {
            if !metadata_path.exists() || !checkpoint_path.exists() {
                return Err(ProductionError::Integrity(
                    "checkpoint metadata and payload must both exist".into(),
                ));
            }
            let metadata: CheckpointMetadata = serde_json::from_slice(&fs::read(metadata_path)?)
                .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
            let bytes = fs::read(checkpoint_path)?;
            if sha256_hex(&bytes) != metadata.sha256 {
                return Err(ProductionError::Integrity(
                    "checkpoint digest mismatch".into(),
                ));
            }
            (Some(bytes), Some(metadata))
        } else {
            (None, None)
        };
        let last_sequence = checkpoint_metadata
            .as_ref()
            .map_or(0, |metadata| metadata.last_sequence);
        let operations = self
            .records()?
            .into_iter()
            .filter(|record| record.sequence > last_sequence)
            .collect();
        Ok(RecoveryState {
            checkpoint,
            checkpoint_metadata,
            operations,
        })
    }

    /// Compact the journal by retaining only records newer than `sequence`.
    pub fn compact(&self, sequence: u64) -> Result<(), ProductionError> {
        let records: Vec<JournalRecord> = self
            .records()?
            .into_iter()
            .filter(|record| record.sequence > sequence)
            .collect();
        let mut encoded = Vec::new();
        for record in records {
            serde_json::to_writer(&mut encoded, &record)
                .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
            encoded.push(b'\n');
        }
        atomic_write(&self.directory.join(JOURNAL_FILE), &encoded)
    }
}

fn read_records(path: &Path) -> Result<Vec<JournalRecord>, ProductionError> {
    if !path.exists() {
        return Ok(Vec::new());
    }
    let reader = BufReader::new(File::open(path)?);
    let mut records = Vec::new();
    let mut previous = 0;
    for (index, line) in reader.lines().enumerate() {
        let line = line?;
        if line.trim().is_empty() {
            continue;
        }
        let record: JournalRecord = serde_json::from_str(&line).map_err(|error| {
            ProductionError::InvalidData(format!("journal line {}: {error}", index + 1))
        })?;
        record.verify()?;
        if record.sequence <= previous {
            return Err(ProductionError::Integrity(format!(
                "journal sequence {} is not monotonic",
                record.sequence
            )));
        }
        previous = record.sequence;
        records.push(record);
    }
    Ok(records)
}

fn atomic_write(path: &Path, bytes: &[u8]) -> Result<(), ProductionError> {
    let parent = path
        .parent()
        .ok_or_else(|| ProductionError::InvalidData("path has no parent".into()))?;
    fs::create_dir_all(parent)?;
    let temporary = parent.join(format!(
        ".{}.{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("loom"),
        std::process::id()
    ));
    {
        let mut file = File::create(&temporary)?;
        file.write_all(bytes)?;
        file.flush()?;
        file.sync_all()?;
    }
    if path.exists() {
        fs::remove_file(path)?;
    }
    fs::rename(&temporary, path)?;
    sync_directory(parent)?;
    Ok(())
}

#[cfg(unix)]
fn sync_directory(path: &Path) -> Result<(), ProductionError> {
    File::open(path)?.sync_all()?;
    Ok(())
}

#[cfg(not(unix))]
fn sync_directory(_path: &Path) -> Result<(), ProductionError> {
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut output = String::with_capacity(64);
    for byte in digest {
        use std::fmt::Write as _;
        let _ = write!(output, "{byte:02x}");
    }
    output
}

fn unix_time_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

/// Runtime-localized message catalogue with deterministic fallback.
#[derive(Debug, Clone, Default)]
pub struct LocaleCatalog {
    default_locale: String,
    messages: BTreeMap<String, BTreeMap<String, String>>,
}

impl LocaleCatalog {
    /// Create a catalogue with the given default locale.
    pub fn new(default_locale: impl Into<String>) -> Self {
        Self {
            default_locale: normalize_locale(&default_locale.into()),
            messages: BTreeMap::new(),
        }
    }

    /// Add or replace one locale from a JSON object of string values.
    pub fn load_json(&mut self, locale: &str, json: &str) -> Result<(), ProductionError> {
        let parsed: BTreeMap<String, String> = serde_json::from_str(json)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        self.messages.insert(normalize_locale(locale), parsed);
        Ok(())
    }

    /// Resolve a message using exact locale, language-only, then default.
    pub fn resolve(&self, locale: &str, key: &str) -> Option<&str> {
        let locale = normalize_locale(locale);
        let language = locale.split('-').next().unwrap_or(&locale);
        for candidate in [locale.as_str(), language, self.default_locale.as_str()] {
            if let Some(value) = self
                .messages
                .get(candidate)
                .and_then(|messages| messages.get(key))
            {
                return Some(value);
            }
        }
        None
    }

    /// Resolve and replace `{name}` placeholders from a deterministic map.
    pub fn format(
        &self,
        locale: &str,
        key: &str,
        arguments: &BTreeMap<String, String>,
    ) -> Option<String> {
        let mut output = self.resolve(locale, key)?.to_string();
        for (name, value) in arguments {
            output = output.replace(&format!("{{{name}}}"), value);
        }
        Some(output)
    }

    /// Locale identifiers currently loaded.
    pub fn locales(&self) -> impl Iterator<Item = &str> {
        self.messages.keys().map(String::as_str)
    }
}

fn normalize_locale(locale: &str) -> String {
    locale.trim().replace('_', "-").to_ascii_lowercase()
}

/// One measured span.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct TraceSample {
    /// Span category, such as `render.preview`.
    pub category: String,
    /// Duration in nanoseconds.
    pub duration_ns: u128,
}

/// Aggregate latency statistics for a category.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct LatencySummary {
    /// Sample count.
    pub count: usize,
    /// Minimum duration.
    pub min: Duration,
    /// Median duration.
    pub p50: Duration,
    /// 95th percentile duration.
    pub p95: Duration,
    /// 99th percentile duration.
    pub p99: Duration,
    /// Maximum duration.
    pub max: Duration,
}

/// Thread-safe in-process trace recorder.
#[derive(Debug, Clone, Default)]
pub struct TraceRecorder {
    samples: Arc<Mutex<Vec<TraceSample>>>,
}

impl TraceRecorder {
    /// Start a span. It is recorded when the returned guard is dropped.
    pub fn span(&self, category: impl Into<String>) -> TraceSpan {
        TraceSpan {
            category: category.into(),
            started: Instant::now(),
            recorder: self.clone(),
        }
    }

    /// Add a pre-measured sample.
    pub fn record(
        &self,
        category: impl Into<String>,
        duration: Duration,
    ) -> Result<(), ProductionError> {
        self.samples
            .lock()
            .map_err(|_| ProductionError::Poisoned)?
            .push(TraceSample {
                category: category.into(),
                duration_ns: duration.as_nanos(),
            });
        Ok(())
    }

    /// Snapshot all current samples.
    pub fn samples(&self) -> Result<Vec<TraceSample>, ProductionError> {
        Ok(self
            .samples
            .lock()
            .map_err(|_| ProductionError::Poisoned)?
            .clone())
    }

    /// Compute latency percentiles for one category.
    pub fn summary(&self, category: &str) -> Result<Option<LatencySummary>, ProductionError> {
        let mut values: Vec<u128> = self
            .samples()?
            .into_iter()
            .filter(|sample| sample.category == category)
            .map(|sample| sample.duration_ns)
            .collect();
        if values.is_empty() {
            return Ok(None);
        }
        values.sort_unstable();
        Ok(Some(LatencySummary {
            count: values.len(),
            min: duration_from_nanos(values[0]),
            p50: duration_from_nanos(percentile(&values, 50)),
            p95: duration_from_nanos(percentile(&values, 95)),
            p99: duration_from_nanos(percentile(&values, 99)),
            max: duration_from_nanos(*values.last().unwrap_or(&values[0])),
        }))
    }

    /// Serialize a deterministic JSON trace snapshot.
    pub fn to_json(&self) -> Result<String, ProductionError> {
        serde_json::to_string_pretty(&self.samples()?)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))
    }
}

/// RAII performance span.
#[derive(Debug)]
pub struct TraceSpan {
    category: String,
    started: Instant,
    recorder: TraceRecorder,
}

impl Drop for TraceSpan {
    fn drop(&mut self) {
        let _ = self
            .recorder
            .record(self.category.clone(), self.started.elapsed());
    }
}

fn percentile(values: &[u128], percentile: usize) -> u128 {
    let index = ((values.len() - 1) * percentile).div_ceil(100);
    values[index.min(values.len() - 1)]
}

fn duration_from_nanos(nanos: u128) -> Duration {
    Duration::from_nanos(nanos.min(u64::MAX as u128) as u64)
}

/// Accessibility metadata for one interactive UI node.
#[derive(Debug, Clone, PartialEq)]
pub struct AccessibilityNode {
    /// Stable accessibility identifier.
    pub id: String,
    /// Semantic role.
    pub role: String,
    /// Spoken label.
    pub label: String,
    /// Optional spoken description.
    pub description: String,
    /// Logical width in device-independent pixels.
    pub width: f32,
    /// Logical height in device-independent pixels.
    pub height: f32,
    /// Foreground relative luminance in the range 0..=1.
    pub foreground_luminance: f32,
    /// Background relative luminance in the range 0..=1.
    pub background_luminance: f32,
    /// Whether keyboard focus can reach the node.
    pub keyboard_focusable: bool,
}

/// Accessibility audit finding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AccessibilityFinding {
    /// Node id, or `document` for global findings.
    pub node_id: String,
    /// Stable rule identifier.
    pub rule: String,
    /// Human-readable failure description.
    pub message: String,
}

/// Audit interactive nodes for baseline WCAG-oriented requirements.
pub fn audit_accessibility(nodes: &[AccessibilityNode]) -> Vec<AccessibilityFinding> {
    let mut findings = Vec::new();
    let mut ids = BTreeSet::new();
    for node in nodes {
        if node.id.trim().is_empty() {
            findings.push(finding(node, "id.required", "interactive node has no id"));
        } else if !ids.insert(node.id.clone()) {
            findings.push(finding(node, "id.unique", "accessibility id is duplicated"));
        }
        if node.role.trim().is_empty() {
            findings.push(finding(node, "role.required", "semantic role is missing"));
        }
        if node.label.trim().is_empty() {
            findings.push(finding(node, "label.required", "spoken label is missing"));
        }
        if node.width < 24.0 || node.height < 24.0 {
            findings.push(finding(
                node,
                "target.minimum",
                "interactive target is smaller than 24 by 24 logical pixels",
            ));
        }
        if !node.keyboard_focusable {
            findings.push(finding(
                node,
                "keyboard.reachable",
                "interactive node cannot receive keyboard focus",
            ));
        }
        let ratio = contrast_ratio(node.foreground_luminance, node.background_luminance);
        if ratio < 4.5 {
            findings.push(finding(
                node,
                "contrast.normal-text",
                &format!("contrast ratio {ratio:.2}:1 is below 4.5:1"),
            ));
        }
    }
    findings
}

fn finding(node: &AccessibilityNode, rule: &str, message: &str) -> AccessibilityFinding {
    AccessibilityFinding {
        node_id: if node.id.is_empty() {
            "document".into()
        } else {
            node.id.clone()
        },
        rule: rule.into(),
        message: message.into(),
    }
}

fn contrast_ratio(first: f32, second: f32) -> f32 {
    let light = first.max(second).clamp(0.0, 1.0);
    let dark = first.min(second).clamp(0.0, 1.0);
    (light + 0.05) / (dark + 0.05)
}

/// Operating-system family supported by a release artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum OperatingSystem {
    /// Linux desktop.
    Linux,
    /// Microsoft Windows.
    Windows,
    /// Apple macOS.
    MacOs,
}

/// CPU architecture supported by a release artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Architecture {
    /// 64-bit x86.
    X86_64,
    /// 64-bit Arm.
    Aarch64,
}

/// One installer or portable-package target.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InstallerTarget {
    /// Operating system.
    pub operating_system: OperatingSystem,
    /// CPU architecture.
    pub architecture: Architecture,
    /// Package kind, such as `appimage`, `deb`, `msi`, or `dmg`.
    pub package_kind: String,
    /// Whether the artifact must be code-signed.
    pub signing_required: bool,
    /// Whether an automatic updater is supported.
    pub updates_supported: bool,
}

/// Validate that a release matrix covers mandatory desktop targets and package
/// invariants. Returns human-readable errors rather than panicking.
pub fn validate_release_matrix(targets: &[InstallerTarget]) -> Vec<String> {
    let mut errors = Vec::new();
    let mut identities = BTreeSet::new();
    for target in targets {
        let identity = (
            target.operating_system,
            target.architecture,
            target.package_kind.to_ascii_lowercase(),
        );
        if !identities.insert(identity) {
            errors.push(format!(
                "duplicate {:?}/{:?}/{} target",
                target.operating_system, target.architecture, target.package_kind
            ));
        }
        if target.package_kind.trim().is_empty() {
            errors.push("package kind must not be empty".into());
        }
        if matches!(
            target.operating_system,
            OperatingSystem::Windows | OperatingSystem::MacOs
        ) && !target.signing_required
        {
            errors.push(format!(
                "{:?} packages must require code signing",
                target.operating_system
            ));
        }
    }
    for required in [
        (OperatingSystem::Linux, Architecture::X86_64),
        (OperatingSystem::Windows, Architecture::X86_64),
        (OperatingSystem::MacOs, Architecture::Aarch64),
    ] {
        if !targets
            .iter()
            .any(|target| (target.operating_system, target.architecture) == required)
        {
            errors.push(format!(
                "missing {:?}/{:?} release target",
                required.0, required.1
            ));
        }
    }
    errors
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn journal_recovers_after_checkpoint_and_rejects_tampering() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Insert", b"first".to_vec())
            .expect("append");
        journal
            .append("two", "Adjust", b"second".to_vec())
            .expect("append");
        journal
            .checkpoint(1, "loom.test/1", b"checkpoint")
            .expect("checkpoint");
        let state = journal.recover().expect("recover");
        assert_eq!(state.checkpoint.as_deref(), Some(b"checkpoint".as_slice()));
        assert_eq!(state.operations.len(), 1);
        assert_eq!(state.operations[0].operation_id, "two");

        let journal_path = temporary.path().join(JOURNAL_FILE);
        let mut bytes = fs::read(&journal_path).expect("read journal");
        let position = bytes
            .iter()
            .position(|byte| *byte == b's')
            .expect("payload byte");
        bytes[position] = b'x';
        fs::write(journal_path, bytes).expect("tamper");
        assert!(RecoveryJournal::open(temporary.path()).is_err());
    }

    #[test]
    fn locale_fallback_and_arguments_are_deterministic() {
        let mut catalog = LocaleCatalog::new("en");
        catalog
            .load_json("en", r#"{"save":"Save {name}","open":"Open"}"#)
            .expect("English");
        catalog
            .load_json("fr", r#"{"open":"Ouvrir"}"#)
            .expect("French");
        assert_eq!(catalog.resolve("fr-CA", "open"), Some("Ouvrir"));
        assert_eq!(catalog.resolve("fr-CA", "save"), Some("Save {name}"));
        let arguments = BTreeMap::from([("name".into(), "Project".into())]);
        assert_eq!(
            catalog.format("fr-CA", "save", &arguments).as_deref(),
            Some("Save Project")
        );
    }

    #[test]
    fn profiler_computes_percentiles() {
        let recorder = TraceRecorder::default();
        for milliseconds in 1..=100 {
            recorder
                .record("preview", Duration::from_millis(milliseconds))
                .expect("record");
        }
        let summary = recorder.summary("preview").expect("summary").expect("data");
        assert_eq!(summary.count, 100);
        assert_eq!(summary.p50, Duration::from_millis(51));
        assert_eq!(summary.p95, Duration::from_millis(96));
        assert_eq!(summary.p99, Duration::from_millis(100));
    }

    #[test]
    fn accessibility_audit_reports_actionable_rules() {
        let node = AccessibilityNode {
            id: "save".into(),
            role: "button".into(),
            label: "".into(),
            description: String::new(),
            width: 18.0,
            height: 18.0,
            foreground_luminance: 0.4,
            background_luminance: 0.5,
            keyboard_focusable: false,
        };
        let rules: BTreeSet<String> = audit_accessibility(&[node])
            .into_iter()
            .map(|finding| finding.rule)
            .collect();
        assert!(rules.contains("label.required"));
        assert!(rules.contains("target.minimum"));
        assert!(rules.contains("keyboard.reachable"));
        assert!(rules.contains("contrast.normal-text"));
    }

    #[test]
    fn release_matrix_requires_all_primary_platforms() {
        let errors = validate_release_matrix(&[InstallerTarget {
            operating_system: OperatingSystem::Linux,
            architecture: Architecture::X86_64,
            package_kind: "appimage".into(),
            signing_required: false,
            updates_supported: true,
        }]);
        assert_eq!(errors.len(), 2);
    }
}
