//! Production services shared by every Loom application.
//!
//! The crate deliberately contains no UI or application-model dependency. It
//! provides durable operation journals, atomic checkpoints, localization
//! fallback, deterministic performance summaries, accessibility auditing, and
//! release-target validation that can be adopted by Writer, Sheets, Present,
//! Photo, Motion, Video, Studio, and Encode.

#![forbid(unsafe_code)]

#[cfg(test)]
mod checkpoint_generation_tests;
mod checkpoint_generations;
/// Deduplicating full-state recovery coordination for Loom applications.
pub mod snapshot;

use checkpoint_generations::{
    checkpoint_generation_metadata_path, checkpoint_generation_payload_path,
    next_checkpoint_generation, publish_checkpoint_pointer, read_checkpoint,
    read_checkpoint_generations, read_checkpoint_sequence, read_checkpoint_state,
    reconcile_checkpoint_generations, CheckpointPointer,
};
#[cfg(windows)]
use checkpoint_generations::{
    read_latest_commit_pointer, CHECKPOINT_COMMIT_PREFIX, CHECKPOINT_COMMIT_SUFFIX,
};

use fs2::FileExt;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

const JOURNAL_FILE: &str = "operations.jsonl";
const CHECKPOINT_LOCK_FILE: &str = ".checkpoint.lock";
const CHECKPOINT_FILE: &str = "checkpoint.bin";
const CHECKPOINT_META_FILE: &str = "checkpoint.json";

/// Exclusive lock shared by every reader and writer of one recovery directory.
///
/// Hold this guard while inspecting or changing recovery files that must not be
/// observed midway through an append or checkpoint publication.
#[must_use = "dropping the guard releases the recovery-directory lock"]
pub struct RecoveryDirectoryLock {
    _file: File,
}

/// Lock a recovery directory using the same `.checkpoint.lock` as
/// [`RecoveryJournal`] and [`snapshot::SnapshotRecovery`].
pub fn lock_recovery_directory(
    directory: impl AsRef<Path>,
) -> Result<RecoveryDirectoryLock, ProductionError> {
    let directory = directory.as_ref();
    fs::create_dir_all(directory)?;
    let lock = OpenOptions::new()
        .create(true)
        .read(true)
        .write(true)
        .truncate(false)
        .open(directory.join(CHECKPOINT_LOCK_FILE))?;
    lock.lock_exclusive()?;
    Ok(RecoveryDirectoryLock { _file: lock })
}

/// Error returned by production-service operations.
#[derive(Debug)]
pub enum ProductionError {
    /// Filesystem failure.
    Io(io::Error),
    /// Invalid serialized state.
    InvalidData(String),
    /// Integrity verification failed.
    Integrity(String),
    /// A synchronization primitive was poisoned.
    Poisoned,
}

impl std::fmt::Display for ProductionError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(error) => write!(formatter, "I/O error: {error}"),
            Self::InvalidData(message) => write!(formatter, "invalid data: {message}"),
            Self::Integrity(message) => write!(formatter, "integrity failure: {message}"),
            Self::Poisoned => write!(formatter, "shared state is poisoned"),
        }
    }
}

impl std::error::Error for ProductionError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(error) => Some(error),
            _ => None,
        }
    }
}

impl From<io::Error> for ProductionError {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

/// One durable, replayable application operation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct JournalRecord {
    /// Monotonically increasing sequence number.
    pub sequence: u64,
    /// Stable operation identifier, normally a UUID generated by the app.
    pub operation_id: String,
    /// Human-readable operation label used by recovery UI.
    pub label: String,
    /// Application-owned serialized command or mutation payload.
    pub payload: Vec<u8>,
    /// Unix timestamp in milliseconds.
    pub timestamp_ms: u128,
    /// Lowercase SHA-256 of the payload.
    pub payload_sha256: String,
}

impl JournalRecord {
    fn verify(&self) -> Result<(), ProductionError> {
        let actual = sha256_hex(&self.payload);
        if actual != self.payload_sha256 {
            return Err(ProductionError::Integrity(format!(
                "operation {} payload digest mismatch",
                self.operation_id
            )));
        }
        Ok(())
    }
}

/// Metadata for the last atomic checkpoint.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CheckpointMetadata {
    /// Last journal sequence represented by the checkpoint.
    pub last_sequence: u64,
    /// SHA-256 of the checkpoint bytes.
    pub sha256: String,
    /// Unix timestamp in milliseconds.
    pub timestamp_ms: u128,
    /// Application schema identifier.
    pub schema: String,
}

/// Recovered checkpoint plus operations that must be replayed after it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RecoveryState {
    /// Last valid checkpoint bytes, when available.
    pub checkpoint: Option<Vec<u8>>,
    /// Checkpoint metadata, when available.
    pub checkpoint_metadata: Option<CheckpointMetadata>,
    /// Verified operations newer than the checkpoint.
    pub operations: Vec<JournalRecord>,
}

/// Crash-safe append-only operation journal with atomic checkpoints.
///
/// A journal write is flushed with `sync_data` before [`append`](Self::append)
/// returns. Checkpoints are written to sibling temporary files, synced, and
/// atomically renamed. Corrupt records are rejected rather than silently
/// replayed.
#[derive(Debug)]
pub struct RecoveryJournal {
    directory: PathBuf,
    next_sequence: u64,
}

impl RecoveryJournal {
    /// Open or create a journal directory and validate all existing records.
    ///
    /// A crash that interrupted an append can leave a torn final line that
    /// was never durably synced. Open tolerates exactly that case: the
    /// verified prefix is kept, the torn tail is dropped, and the journal is
    /// repaired in place so later appends cannot resurrect the torn line.
    /// Any other damage (interior corruption, broken checksums, non-monotonic
    /// sequences) still fails loudly.
    pub fn open(directory: impl AsRef<Path>) -> Result<Self, ProductionError> {
        let directory = directory.as_ref().to_path_buf();
        fs::create_dir_all(&directory)?;
        let _recovery_lock = lock_recovery_writes(&directory)?;
        let checkpoint_state = read_checkpoint_state(&directory)?;
        let read = read_records_at(&directory.join(JOURNAL_FILE), true)?;
        if read.skipped_tail {
            repair_journal(&directory, &read.records)?;
        }
        reconcile_checkpoint_generations(&directory, &checkpoint_state)?;
        let journal_sequence = read.records.last().map(|record| record.sequence);
        let checkpoint_sequence = checkpoint_state
            .metadata
            .as_ref()
            .map(|metadata| metadata.last_sequence);
        let highest_sequence = journal_sequence
            .into_iter()
            .chain(checkpoint_sequence)
            .max();
        let next_sequence = match highest_sequence {
            Some(sequence) => checked_next_sequence(sequence)?,
            None => 1,
        };
        Ok(Self {
            directory,
            next_sequence,
        })
    }

    /// Journal root directory.
    pub fn directory(&self) -> &Path {
        &self.directory
    }

    pub(crate) fn clear_recovery_data(&self) -> Result<(), ProductionError> {
        let _recovery_lock = lock_recovery_writes(&self.directory)?;
        for entry in fs::read_dir(&self.directory)? {
            let entry = entry?;
            if entry.file_name() == CHECKPOINT_LOCK_FILE {
                continue;
            }
            let path = entry.path();
            if fs::symlink_metadata(&path)?.file_type().is_dir() {
                fs::remove_dir_all(path)?;
            } else {
                fs::remove_file(path)?;
            }
        }
        Ok(())
    }

    /// Append one operation and durably flush it before returning.
    pub fn append(
        &mut self,
        operation_id: impl Into<String>,
        label: impl Into<String>,
        payload: Vec<u8>,
    ) -> Result<JournalRecord, ProductionError> {
        let _recovery_lock = lock_recovery_writes(&self.directory)?;
        let path = self.directory.join(JOURNAL_FILE);
        let read = read_records_at(&path, true)?;
        if read.skipped_tail {
            repair_journal(&self.directory, &read.records)?;
        }
        let journal_sequence = read.records.last().map(|record| record.sequence);
        let checkpoint_sequence = read_checkpoint_sequence(&self.directory)?;
        let disk_next_sequence = match journal_sequence
            .into_iter()
            .chain(checkpoint_sequence)
            .max()
        {
            Some(sequence) => checked_next_sequence(sequence)?,
            None => 1,
        };
        let sequence = self.next_sequence.max(disk_next_sequence);
        let next_sequence = checked_next_sequence(sequence)?;
        let record = JournalRecord {
            sequence,
            operation_id: operation_id.into(),
            label: label.into(),
            payload_sha256: sha256_hex(&payload),
            payload,
            timestamp_ms: unix_time_ms(),
        };
        record.verify()?;
        let encoded = serde_json::to_vec(&record)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        let existed = path.exists();
        if existed {
            let mut file = OpenOptions::new().append(true).open(path)?;
            file.write_all(&encoded)?;
            file.write_all(b"\n")?;
            file.flush()?;
            file.sync_data()?;
        } else {
            // AtomicFile also syncs the parent directory when it publishes a
            // new file, so the first successful append survives a system
            // crash with its directory entry intact.
            let mut first_record = encoded;
            first_record.push(b'\n');
            atomic_write(&path, &first_record)?;
        }
        self.next_sequence = next_sequence;
        Ok(record)
    }

    /// Return every verified journal record.
    pub fn records(&self) -> Result<Vec<JournalRecord>, ProductionError> {
        let _recovery_lock = lock_recovery_writes(&self.directory)?;
        let read = read_records_at(&self.directory.join(JOURNAL_FILE), true)?;
        if read.skipped_tail {
            repair_journal(&self.directory, &read.records)?;
        }
        Ok(read.records)
    }

    /// Atomically write an application checkpoint.
    pub fn checkpoint(
        &self,
        last_sequence: u64,
        schema: impl Into<String>,
        bytes: &[u8],
    ) -> Result<CheckpointMetadata, ProductionError> {
        // All processes writing recovery data use one lock, so generation
        // selection and pointer publication happen in one order.
        let _recovery_lock = lock_recovery_writes(&self.directory)?;
        let journal_read = read_records_at(&self.directory.join(JOURNAL_FILE), true)?;
        if journal_read.skipped_tail {
            repair_journal(&self.directory, &journal_read.records)?;
        }
        let current_checkpoint = read_checkpoint_state(&self.directory)?;
        let current_checkpoint_sequence = current_checkpoint
            .metadata
            .as_ref()
            .map(|metadata| metadata.last_sequence);
        if let Some(current_sequence) = current_checkpoint_sequence {
            if last_sequence < current_sequence {
                return Err(ProductionError::Integrity(format!(
                    "checkpoint sequence {last_sequence} cannot replace newer sequence {current_sequence}"
                )));
            }
        }
        let highest_saved_sequence = journal_read
            .records
            .last()
            .map(|record| record.sequence)
            .into_iter()
            .chain(current_checkpoint_sequence)
            .max()
            .unwrap_or(0);
        if last_sequence > highest_saved_sequence {
            return Err(ProductionError::Integrity(format!(
                "checkpoint sequence {last_sequence} is newer than saved recovery data {highest_saved_sequence}"
            )));
        }
        reconcile_checkpoint_generations(&self.directory, &current_checkpoint)?;

        let metadata = CheckpointMetadata {
            last_sequence,
            sha256: sha256_hex(bytes),
            timestamp_ms: unix_time_ms(),
            schema: schema.into(),
        };
        let metadata_bytes = serde_json::to_vec_pretty(&metadata)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        let generation = next_checkpoint_generation(&self.directory)?;
        let payload_path = checkpoint_generation_payload_path(&self.directory, generation);
        let metadata_path = checkpoint_generation_metadata_path(&self.directory, generation);

        // A generation is complete before its pointer is published. A failure
        // in either write leaves the previous pointer and journal untouched.
        atomic_write(&payload_path, bytes)?;
        atomic_write(&metadata_path, &metadata_bytes)?;
        let (verified_bytes, verified_metadata) =
            read_checkpoint_generations(&self.directory, generation)?;
        if verified_bytes != bytes || verified_metadata != metadata {
            return Err(ProductionError::Integrity(
                "checkpoint generation changed before publication".into(),
            ));
        }

        let pointer = CheckpointPointer {
            generation,
            last_sequence,
            sha256: metadata.sha256.clone(),
            timestamp_ms: metadata.timestamp_ms,
            schema: metadata.schema.clone(),
            previous_generation: current_checkpoint
                .pointer
                .as_ref()
                .map(|pointer| pointer.generation),
        };
        let pointer_bytes = serde_json::to_vec_pretty(&pointer)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        publish_checkpoint_pointer(&self.directory, generation, &pointer_bytes)?;
        Ok(metadata)
    }

    /// Load the last valid checkpoint and all operations after it.
    pub fn recover(&self) -> Result<RecoveryState, ProductionError> {
        self.recover_with_checkpoint_hook(|| {})
    }

    fn recover_with_checkpoint_hook(
        &self,
        after_checkpoint_read: impl FnOnce(),
    ) -> Result<RecoveryState, ProductionError> {
        let _recovery_lock = lock_recovery_writes(&self.directory)?;
        let (checkpoint, checkpoint_metadata) = read_checkpoint(&self.directory)?;
        after_checkpoint_read();
        let last_sequence = checkpoint_metadata
            .as_ref()
            .map_or(0, |metadata| metadata.last_sequence);
        let journal_read = read_records_at(&self.directory.join(JOURNAL_FILE), true)?;
        if journal_read.skipped_tail {
            repair_journal(&self.directory, &journal_read.records)?;
        }
        let operations = journal_read
            .records
            .into_iter()
            .filter(|record| record.sequence > last_sequence)
            .collect();
        Ok(RecoveryState {
            checkpoint,
            checkpoint_metadata,
            operations,
        })
    }

    /// Compact the journal by retaining only records newer than `sequence`.
    pub fn compact(&self, sequence: u64) -> Result<(), ProductionError> {
        let _recovery_lock = lock_recovery_writes(&self.directory)?;
        let checkpoint_state = read_checkpoint_state(&self.directory)?;
        let checkpoint_sequence = checkpoint_state
            .metadata
            .as_ref()
            .map_or(0, |metadata| metadata.last_sequence);
        if sequence > checkpoint_sequence {
            return Err(ProductionError::Integrity(format!(
                "cannot compact through sequence {sequence}; durable checkpoint is {checkpoint_sequence}"
            )));
        }
        let journal_read = read_records_at(&self.directory.join(JOURNAL_FILE), true)?;
        if journal_read.skipped_tail {
            repair_journal(&self.directory, &journal_read.records)?;
        }
        compact_journal_with(&self.directory, sequence, atomic_write)?;
        reconcile_checkpoint_generations(&self.directory, &checkpoint_state)
    }
}

/// Outcome of reading a journal, including whether a torn tail was dropped.
struct JournalRead {
    records: Vec<JournalRecord>,
    skipped_tail: bool,
}

fn checked_next_sequence(sequence: u64) -> Result<u64, ProductionError> {
    sequence.checked_add(1).ok_or_else(|| {
        ProductionError::Integrity("journal sequence is exhausted at u64::MAX".into())
    })
}

fn read_records(path: &Path) -> Result<Vec<JournalRecord>, ProductionError> {
    Ok(read_records_at(path, false)?.records)
}

/// Read journal records. When `tolerant_tail` is set, a final line that fails
/// to parse is treated as a torn append tail rather than an error.
fn read_records_at(path: &Path, tolerant_tail: bool) -> Result<JournalRead, ProductionError> {
    if !path.exists() {
        return Ok(JournalRead {
            records: Vec::new(),
            skipped_tail: false,
        });
    }
    let bytes = fs::read(path)?;
    let text = String::from_utf8(bytes)
        .map_err(|error| ProductionError::InvalidData(format!("journal is not UTF-8: {error}")))?;
    let mut raw_lines: Vec<&str> = text.lines().collect();
    let mut records = Vec::new();
    let mut previous = 0;
    let mut skipped_tail = false;
    if !text.is_empty() && !text.ends_with('\n') {
        if tolerant_tail {
            // The newline is the append's commit marker. Without it, even a
            // valid JSON object may be a write interrupted before sync.
            raw_lines.pop();
            skipped_tail = true;
        } else {
            return Err(ProductionError::InvalidData(
                "journal ends with an incomplete record delimiter".into(),
            ));
        }
    }
    for (index, line) in raw_lines.iter().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let is_last = index + 1 == raw_lines.len();
        let record: JournalRecord = match serde_json::from_str(line) {
            Ok(record) => record,
            Err(error) => {
                if tolerant_tail && is_last {
                    skipped_tail = true;
                    break;
                }
                return Err(ProductionError::InvalidData(format!(
                    "journal line {}: {error}",
                    index + 1
                )));
            }
        };
        record.verify()?;
        if record.sequence <= previous {
            return Err(ProductionError::Integrity(format!(
                "journal sequence {} is not monotonic",
                record.sequence
            )));
        }
        previous = record.sequence;
        records.push(record);
    }
    Ok(JournalRead {
        records,
        skipped_tail,
    })
}

/// Persist only the verified prefix of a journal, dropping a torn tail so a
/// later crash cannot make it appear interior to valid records.
fn repair_journal(directory: &Path, records: &[JournalRecord]) -> Result<(), ProductionError> {
    repair_journal_with(directory, records, atomic_write)
}

fn lock_recovery_writes(directory: &Path) -> Result<RecoveryDirectoryLock, ProductionError> {
    lock_recovery_directory(directory)
}

fn compact_journal_with(
    directory: &Path,
    sequence: u64,
    write: impl FnOnce(&Path, &[u8]) -> Result<(), ProductionError>,
) -> Result<(), ProductionError> {
    let records: Vec<JournalRecord> = read_records(&directory.join(JOURNAL_FILE))?
        .into_iter()
        .filter(|record| record.sequence > sequence)
        .collect();
    write_journal_with(directory, &records, write)
}

fn repair_journal_with(
    directory: &Path,
    records: &[JournalRecord],
    write: impl FnOnce(&Path, &[u8]) -> Result<(), ProductionError>,
) -> Result<(), ProductionError> {
    write_journal_with(directory, records, write)
}

fn write_journal_with(
    directory: &Path,
    records: &[JournalRecord],
    write: impl FnOnce(&Path, &[u8]) -> Result<(), ProductionError>,
) -> Result<(), ProductionError> {
    let mut encoded = Vec::new();
    for record in records {
        serde_json::to_writer(&mut encoded, record)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        encoded.push(b'\n');
    }
    write(&directory.join(JOURNAL_FILE), &encoded)
}

fn atomic_write(path: &Path, bytes: &[u8]) -> Result<(), ProductionError> {
    atomic_write_with(path, |file| file.write_all(bytes))
}

fn atomic_write_with(
    path: &Path,
    write: impl FnOnce(&mut File) -> io::Result<()>,
) -> Result<(), ProductionError> {
    let parent = path
        .parent()
        .ok_or_else(|| ProductionError::InvalidData("path has no parent".into()))?;
    fs::create_dir_all(parent)?;
    atomicwrites::AtomicFile::new(path, atomicwrites::AllowOverwrite)
        .write(write)
        .map_err(io::Error::from)?;
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut output = String::with_capacity(64);
    for byte in digest {
        use std::fmt::Write as _;
        let _ = write!(output, "{byte:02x}");
    }
    output
}

fn unix_time_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

/// Runtime-localized message catalogue with deterministic fallback.
#[derive(Debug, Clone, Default)]
pub struct LocaleCatalog {
    default_locale: String,
    messages: BTreeMap<String, BTreeMap<String, String>>,
}

impl LocaleCatalog {
    /// Create a catalogue with the given default locale.
    pub fn new(default_locale: impl Into<String>) -> Self {
        Self {
            default_locale: normalize_locale(&default_locale.into()),
            messages: BTreeMap::new(),
        }
    }

    /// Add or replace one locale from a JSON object of string values.
    pub fn load_json(&mut self, locale: &str, json: &str) -> Result<(), ProductionError> {
        let parsed: BTreeMap<String, String> = serde_json::from_str(json)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))?;
        self.messages.insert(normalize_locale(locale), parsed);
        Ok(())
    }

    /// Resolve a message using exact locale, language-only, then default.
    pub fn resolve(&self, locale: &str, key: &str) -> Option<&str> {
        let locale = normalize_locale(locale);
        let language = locale.split('-').next().unwrap_or(&locale);
        for candidate in [locale.as_str(), language, self.default_locale.as_str()] {
            if let Some(value) = self
                .messages
                .get(candidate)
                .and_then(|messages| messages.get(key))
            {
                return Some(value);
            }
        }
        None
    }

    /// Resolve and replace `{name}` placeholders from a deterministic map.
    pub fn format(
        &self,
        locale: &str,
        key: &str,
        arguments: &BTreeMap<String, String>,
    ) -> Option<String> {
        let mut output = self.resolve(locale, key)?.to_string();
        for (name, value) in arguments {
            output = output.replace(&format!("{{{name}}}"), value);
        }
        Some(output)
    }

    /// Locale identifiers currently loaded.
    pub fn locales(&self) -> impl Iterator<Item = &str> {
        self.messages.keys().map(String::as_str)
    }
}

fn normalize_locale(locale: &str) -> String {
    locale.trim().replace('_', "-").to_ascii_lowercase()
}

/// One measured span.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct TraceSample {
    /// Span category, such as `render.preview`.
    pub category: String,
    /// Duration in nanoseconds.
    pub duration_ns: u128,
}

/// Aggregate latency statistics for a category.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct LatencySummary {
    /// Sample count.
    pub count: usize,
    /// Minimum duration.
    pub min: Duration,
    /// Median duration.
    pub p50: Duration,
    /// 95th percentile duration.
    pub p95: Duration,
    /// 99th percentile duration.
    pub p99: Duration,
    /// Maximum duration.
    pub max: Duration,
}

/// Thread-safe in-process trace recorder.
#[derive(Debug, Clone, Default)]
pub struct TraceRecorder {
    samples: Arc<Mutex<Vec<TraceSample>>>,
}

impl TraceRecorder {
    /// Start a span. It is recorded when the returned guard is dropped.
    pub fn span(&self, category: impl Into<String>) -> TraceSpan {
        TraceSpan {
            category: category.into(),
            started: Instant::now(),
            recorder: self.clone(),
        }
    }

    /// Add a pre-measured sample.
    pub fn record(
        &self,
        category: impl Into<String>,
        duration: Duration,
    ) -> Result<(), ProductionError> {
        self.samples
            .lock()
            .map_err(|_| ProductionError::Poisoned)?
            .push(TraceSample {
                category: category.into(),
                duration_ns: duration.as_nanos(),
            });
        Ok(())
    }

    /// Snapshot all current samples.
    pub fn samples(&self) -> Result<Vec<TraceSample>, ProductionError> {
        Ok(self
            .samples
            .lock()
            .map_err(|_| ProductionError::Poisoned)?
            .clone())
    }

    /// Compute latency percentiles for one category.
    pub fn summary(&self, category: &str) -> Result<Option<LatencySummary>, ProductionError> {
        let mut values: Vec<u128> = self
            .samples()?
            .into_iter()
            .filter(|sample| sample.category == category)
            .map(|sample| sample.duration_ns)
            .collect();
        if values.is_empty() {
            return Ok(None);
        }
        values.sort_unstable();
        Ok(Some(LatencySummary {
            count: values.len(),
            min: duration_from_nanos(values[0]),
            p50: duration_from_nanos(percentile(&values, 50)),
            p95: duration_from_nanos(percentile(&values, 95)),
            p99: duration_from_nanos(percentile(&values, 99)),
            max: duration_from_nanos(*values.last().unwrap_or(&values[0])),
        }))
    }

    /// Serialize a deterministic JSON trace snapshot.
    pub fn to_json(&self) -> Result<String, ProductionError> {
        serde_json::to_string_pretty(&self.samples()?)
            .map_err(|error| ProductionError::InvalidData(error.to_string()))
    }
}

/// RAII performance span.
#[derive(Debug)]
pub struct TraceSpan {
    category: String,
    started: Instant,
    recorder: TraceRecorder,
}

impl Drop for TraceSpan {
    fn drop(&mut self) {
        let _ = self
            .recorder
            .record(self.category.clone(), self.started.elapsed());
    }
}

fn percentile(values: &[u128], percentile: usize) -> u128 {
    let index = ((values.len() - 1) * percentile).div_ceil(100);
    values[index.min(values.len() - 1)]
}

fn duration_from_nanos(nanos: u128) -> Duration {
    Duration::from_nanos(nanos.min(u64::MAX as u128) as u64)
}

/// Accessibility metadata for one interactive UI node.
#[derive(Debug, Clone, PartialEq)]
pub struct AccessibilityNode {
    /// Stable accessibility identifier.
    pub id: String,
    /// Semantic role.
    pub role: String,
    /// Spoken label.
    pub label: String,
    /// Optional spoken description.
    pub description: String,
    /// Logical width in device-independent pixels.
    pub width: f32,
    /// Logical height in device-independent pixels.
    pub height: f32,
    /// Foreground relative luminance in the range 0..=1.
    pub foreground_luminance: f32,
    /// Background relative luminance in the range 0..=1.
    pub background_luminance: f32,
    /// Whether keyboard focus can reach the node.
    pub keyboard_focusable: bool,
}

/// Accessibility audit finding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AccessibilityFinding {
    /// Node id, or `document` for global findings.
    pub node_id: String,
    /// Stable rule identifier.
    pub rule: String,
    /// Human-readable failure description.
    pub message: String,
}

/// Audit interactive nodes for baseline WCAG-oriented requirements.
pub fn audit_accessibility(nodes: &[AccessibilityNode]) -> Vec<AccessibilityFinding> {
    let mut findings = Vec::new();
    let mut ids = BTreeSet::new();
    for node in nodes {
        if node.id.trim().is_empty() {
            findings.push(finding(node, "id.required", "interactive node has no id"));
        } else if !ids.insert(node.id.clone()) {
            findings.push(finding(node, "id.unique", "accessibility id is duplicated"));
        }
        if node.role.trim().is_empty() {
            findings.push(finding(node, "role.required", "semantic role is missing"));
        }
        if node.label.trim().is_empty() {
            findings.push(finding(node, "label.required", "spoken label is missing"));
        }
        if node.width < 24.0 || node.height < 24.0 {
            findings.push(finding(
                node,
                "target.minimum",
                "interactive target is smaller than 24 by 24 logical pixels",
            ));
        }
        if !node.keyboard_focusable {
            findings.push(finding(
                node,
                "keyboard.reachable",
                "interactive node cannot receive keyboard focus",
            ));
        }
        let ratio = contrast_ratio(node.foreground_luminance, node.background_luminance);
        if ratio < 4.5 {
            findings.push(finding(
                node,
                "contrast.normal-text",
                &format!("contrast ratio {ratio:.2}:1 is below 4.5:1"),
            ));
        }
    }
    findings
}

fn finding(node: &AccessibilityNode, rule: &str, message: &str) -> AccessibilityFinding {
    AccessibilityFinding {
        node_id: if node.id.is_empty() {
            "document".into()
        } else {
            node.id.clone()
        },
        rule: rule.into(),
        message: message.into(),
    }
}

fn contrast_ratio(first: f32, second: f32) -> f32 {
    let light = first.max(second).clamp(0.0, 1.0);
    let dark = first.min(second).clamp(0.0, 1.0);
    (light + 0.05) / (dark + 0.05)
}

/// Operating-system family supported by a release artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum OperatingSystem {
    /// Linux desktop.
    Linux,
    /// Microsoft Windows.
    Windows,
    /// Apple macOS.
    MacOs,
}

/// CPU architecture supported by a release artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Architecture {
    /// 64-bit x86.
    X86_64,
    /// 64-bit Arm.
    Aarch64,
}

/// One installer or portable-package target.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InstallerTarget {
    /// Operating system.
    pub operating_system: OperatingSystem,
    /// CPU architecture.
    pub architecture: Architecture,
    /// Package kind, such as `appimage`, `deb`, `msi`, or `dmg`.
    pub package_kind: String,
    /// Whether the artifact must be code-signed.
    pub signing_required: bool,
    /// Whether an automatic updater is supported.
    pub updates_supported: bool,
}

/// Validate that a release matrix covers mandatory desktop targets and package
/// invariants. Returns human-readable errors rather than panicking.
pub fn validate_release_matrix(targets: &[InstallerTarget]) -> Vec<String> {
    let mut errors = Vec::new();
    let mut identities = BTreeSet::new();
    for target in targets {
        let identity = (
            target.operating_system,
            target.architecture,
            target.package_kind.to_ascii_lowercase(),
        );
        if !identities.insert(identity) {
            errors.push(format!(
                "duplicate {:?}/{:?}/{} target",
                target.operating_system, target.architecture, target.package_kind
            ));
        }
        if target.package_kind.trim().is_empty() {
            errors.push("package kind must not be empty".into());
        }
        if matches!(
            target.operating_system,
            OperatingSystem::Windows | OperatingSystem::MacOs
        ) && !target.signing_required
        {
            errors.push(format!(
                "{:?} packages must require code signing",
                target.operating_system
            ));
        }
    }
    for required in [
        (OperatingSystem::Linux, Architecture::X86_64),
        (OperatingSystem::Windows, Architecture::X86_64),
        (OperatingSystem::MacOs, Architecture::Aarch64),
    ] {
        if !targets
            .iter()
            .any(|target| (target.operating_system, target.architecture) == required)
        {
            errors.push(format!(
                "missing {:?}/{:?} release target",
                required.0, required.1
            ));
        }
    }
    errors
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recovery_directory_lock_contention_and_release() {
        use fs2::FileExt;
        use std::sync::mpsc;
        use std::thread;

        let temporary = tempfile::tempdir().expect("temporary recovery directory");
        let lock = lock_recovery_directory(temporary.path()).expect("acquire recovery lock");
        let check_handle = OpenOptions::new()
            .read(true)
            .write(true)
            .open(temporary.path().join(CHECKPOINT_LOCK_FILE))
            .expect("open shared lock file");
        assert!(
            check_handle.try_lock_exclusive().is_err(),
            "the public lock must use the journal checkpoint lock"
        );

        let path = temporary.path().to_path_buf();
        let (acquired_tx, acquired_rx) = mpsc::channel();
        let waiter = thread::spawn(move || {
            let _lock = lock_recovery_directory(path).expect("wait for recovery lock");
            acquired_tx.send(()).expect("report lock acquisition");
        });
        assert!(
            acquired_rx
                .recv_timeout(Duration::from_millis(100))
                .is_err(),
            "second handle must wait while the first lock is held"
        );
        drop(lock);
        acquired_rx
            .recv_timeout(Duration::from_secs(5))
            .expect("second handle acquires after release");
        waiter.join().expect("lock waiter thread");
    }

    #[test]
    fn atomic_write_replaces_existing_destination() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let path = temporary.path().join(JOURNAL_FILE);
        fs::write(&path, b"old journal").expect("old journal");

        atomic_write(&path, b"new journal").expect("atomic replacement");

        assert_eq!(fs::read(path).expect("read replacement"), b"new journal");
    }

    #[test]
    fn failed_atomic_write_preserves_existing_destination() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let path = temporary.path().join(JOURNAL_FILE);
        fs::write(&path, b"old journal").expect("old journal");

        let result = atomic_write_with(&path, |file| {
            file.write_all(b"partial new journal")?;
            Err(io::Error::other("injected staging failure"))
        });

        assert!(result.is_err(), "injected failure must be returned");
        assert_eq!(fs::read(path).expect("read old journal"), b"old journal");
    }

    #[test]
    fn failed_atomic_publish_preserves_existing_directory() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let path = temporary.path().join(JOURNAL_FILE);
        fs::create_dir(&path).expect("destination directory");
        let sentinel = path.join("keep.txt");
        fs::write(&sentinel, b"keep me").expect("sentinel");

        assert!(atomic_write(&path, b"replacement file").is_err());
        assert_eq!(fs::read(sentinel).expect("read sentinel"), b"keep me");
    }

    #[test]
    fn failed_compaction_staging_preserves_existing_records() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"first".to_vec())
            .expect("append");
        journal
            .append("two", "Edit", b"second".to_vec())
            .expect("append");

        let result = compact_journal_with(temporary.path(), 1, |path, bytes| {
            atomic_write_with(path, |file| {
                file.write_all(bytes)?;
                Err(io::Error::other("injected compaction staging failure"))
            })
        });

        assert!(result.is_err(), "injected failure must be returned");
        let records = journal.records().expect("read original journal");
        assert_eq!(records.len(), 2);
        assert_eq!(records[0].payload, b"first");
        assert_eq!(records[1].payload, b"second");
    }

    #[test]
    fn failed_torn_tail_repair_preserves_verified_prefix() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"first".to_vec())
            .expect("append");
        journal
            .append("two", "Edit", b"second".to_vec())
            .expect("append");
        let path = temporary.path().join(JOURNAL_FILE);
        let mut file = OpenOptions::new()
            .append(true)
            .open(&path)
            .expect("open journal");
        file.write_all(b"{\"sequence\": 3,")
            .expect("write torn tail");
        file.sync_data().expect("sync torn tail");
        drop(file);

        let original_bytes = fs::read(&path).expect("read journal before repair");
        let read = read_records_at(&path, true).expect("read verified prefix");
        assert!(read.skipped_tail);
        assert_eq!(read.records.len(), 2);

        let result = repair_journal_with(temporary.path(), &read.records, |target, bytes| {
            atomic_write_with(target, |file| {
                file.write_all(bytes)?;
                Err(io::Error::other("injected repair staging failure"))
            })
        });

        assert!(result.is_err(), "injected failure must be returned");
        assert_eq!(
            fs::read(&path).expect("read original journal"),
            original_bytes
        );
        let still_verified = read_records_at(&path, true).expect("read original prefix");
        assert!(still_verified.skipped_tail);
        assert_eq!(still_verified.records.len(), 2);

        repair_journal(temporary.path(), &read.records).expect("repair on retry");
        assert_eq!(journal.records().expect("read repaired journal").len(), 2);
    }

    #[test]
    fn append_from_stale_handle_uses_the_latest_disk_sequence() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut first_handle = RecoveryJournal::open(temporary.path()).expect("first handle");
        let mut stale_handle = RecoveryJournal::open(temporary.path()).expect("stale handle");

        let first = first_handle
            .append("one", "Edit", b"first".to_vec())
            .expect("first append");
        let second = stale_handle
            .append("two", "Edit", b"second".to_vec())
            .expect("append through stale handle");

        assert_eq!(first.sequence, 1);
        assert_eq!(second.sequence, 2);
        let records = stale_handle.records().expect("records");
        assert_eq!(records.len(), 2);
        assert_eq!(records[0].payload, b"first");
        assert_eq!(records[1].payload, b"second");
    }

    #[test]
    fn checkpoint_cannot_claim_unwritten_journal_operations() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let journal = RecoveryJournal::open(temporary.path()).expect("journal");

        let result = journal.checkpoint(1, "loom.test/1", b"not saved");

        assert!(result.is_err(), "checkpoint must not skip a journal record");
        assert!(journal
            .recover()
            .expect("recover no checkpoint")
            .checkpoint
            .is_none());
    }

    #[test]
    fn compaction_cannot_remove_records_newer_than_checkpoint() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"saved".to_vec())
            .expect("append saved operation");
        journal
            .append("two", "Edit", b"unsaved".to_vec())
            .expect("append unsaved operation");
        journal
            .checkpoint(1, "loom.test/1", b"saved")
            .expect("checkpoint saved operation");

        let result = journal.compact(2);

        assert!(result.is_err(), "uncheckpointed data must not be compacted");
        let state = journal.recover().expect("recover preserved operation");
        assert_eq!(state.checkpoint.as_deref(), Some(b"saved".as_slice()));
        assert_eq!(state.operations.len(), 1);
        assert_eq!(state.operations[0].payload, b"unsaved");
    }

    #[test]
    fn concurrent_checkpoints_publish_distinct_generations_in_sequence_order() {
        use std::sync::Barrier;
        use std::thread;

        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"older".to_vec())
            .expect("append older operation");
        journal
            .append("two", "Edit", b"newer".to_vec())
            .expect("append newer operation");
        let journal = Arc::new(journal);
        let barrier = Arc::new(Barrier::new(3));
        let older_journal = Arc::clone(&journal);
        let older_barrier = Arc::clone(&barrier);
        let older = thread::spawn(move || {
            older_barrier.wait();
            older_journal.checkpoint(1, "loom.test/1", b"older")
        });
        let newer_journal = Arc::clone(&journal);
        let newer_barrier = Arc::clone(&barrier);
        let newer = thread::spawn(move || {
            newer_barrier.wait();
            newer_journal.checkpoint(2, "loom.test/1", b"newer")
        });
        barrier.wait();

        let older_result = older.join().expect("older checkpoint thread");
        let newer_result = newer.join().expect("newer checkpoint thread");
        assert!(newer_result.is_ok(), "newer checkpoint must publish");
        if let Err(error) = older_result {
            assert!(
                matches!(error, ProductionError::Integrity(_)),
                "stale checkpoint must be rejected as an integrity error"
            );
        }

        let state = journal.recover().expect("recover newest checkpoint");
        assert_eq!(state.checkpoint.as_deref(), Some(b"newer".as_slice()));
        assert_eq!(
            state.checkpoint_metadata.expect("metadata").last_sequence,
            2
        );
    }

    #[test]
    fn recovery_holds_write_lock_across_checkpoint_and_journal_reads() {
        use fs2::FileExt;

        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"saved".to_vec())
            .expect("append saved operation");
        journal
            .checkpoint(1, "loom.test/1", b"saved")
            .expect("checkpoint");
        journal
            .append("two", "Edit", b"newer operation".to_vec())
            .expect("append newer operation");

        let state = journal
            .recover_with_checkpoint_hook(|| {
                let second_lock = OpenOptions::new()
                    .read(true)
                    .write(true)
                    .open(temporary.path().join(CHECKPOINT_LOCK_FILE))
                    .expect("open second lock handle");
                assert!(
                    second_lock.try_lock_exclusive().is_err(),
                    "writers must remain blocked until both recovery reads finish"
                );
            })
            .expect("recover consistent state");

        assert_eq!(state.checkpoint.as_deref(), Some(b"saved".as_slice()));
        assert_eq!(state.operations.len(), 1);
        assert_eq!(state.operations[0].payload, b"newer operation");
    }

    #[test]
    fn valid_json_without_final_newline_is_dropped_as_uncommitted_tail() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"committed".to_vec())
            .expect("append committed operation");
        journal
            .append("two", "Edit", b"interrupted".to_vec())
            .expect("append interrupted operation");
        let path = temporary.path().join(JOURNAL_FILE);
        let mut bytes = fs::read(&path).expect("read journal");
        assert_eq!(bytes.pop(), Some(b'\n'));
        fs::write(&path, bytes).expect("simulate crash before delimiter");

        let mut reopened =
            RecoveryJournal::open(temporary.path()).expect("repair interrupted tail");
        let records = reopened.records().expect("read repaired journal");
        assert_eq!(records.len(), 1);
        assert_eq!(records[0].payload, b"committed");

        let next = reopened
            .append("three", "Edit", b"next committed".to_vec())
            .expect("append after repair");
        assert_eq!(next.sequence, 2);
        assert_eq!(reopened.records().expect("read final journal").len(), 2);
    }

    #[test]
    fn journal_recovers_after_checkpoint_and_rejects_tampering() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Insert", b"first".to_vec())
            .expect("append");
        journal
            .append("two", "Adjust", b"second".to_vec())
            .expect("append");
        journal
            .checkpoint(1, "loom.test/1", b"checkpoint")
            .expect("checkpoint");
        let state = journal.recover().expect("recover");
        assert_eq!(state.checkpoint.as_deref(), Some(b"checkpoint".as_slice()));
        assert_eq!(state.operations.len(), 1);
        assert_eq!(state.operations[0].operation_id, "two");

        let journal_path = temporary.path().join(JOURNAL_FILE);
        let mut bytes = fs::read(&journal_path).expect("read journal");
        let position = bytes
            .iter()
            .position(|byte| *byte == b's')
            .expect("payload byte");
        bytes[position] = b'x';
        fs::write(journal_path, bytes).expect("tamper");
        assert!(RecoveryJournal::open(temporary.path()).is_err());
    }

    #[test]
    fn checkpoint_generation_failure_preserves_previous_checkpoint_and_journal() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"old contents".to_vec())
            .expect("append");
        journal
            .checkpoint(1, "loom.test/1", b"old contents")
            .expect("checkpoint");
        journal
            .append("two", "Edit", b"latest contents".to_vec())
            .expect("append");

        // This is the legacy metadata-temp location. Publishing the new
        // pointer must fail before it can replace the old pointer.
        let blocker = temporary.path().join(format!(
            ".{CHECKPOINT_META_FILE}.{}.tmp",
            std::process::id()
        ));
        fs::create_dir(&blocker).expect("block metadata temp");
        assert!(journal
            .checkpoint(2, "loom.test/1", b"latest contents")
            .is_err());
        fs::remove_dir(&blocker).expect("remove metadata blocker");
        drop(journal);

        let reopened = RecoveryJournal::open(temporary.path()).expect("reopen");
        let state = reopened.recover().expect("recover previous generation");
        assert_eq!(
            state.checkpoint.as_deref(),
            Some(b"old contents".as_slice())
        );
        assert_eq!(state.operations.len(), 1);
        assert_eq!(state.operations[0].payload, b"latest contents");
    }

    #[test]
    fn journal_sequence_starts_after_checkpoint_sequence() {
        let temporary = tempfile::tempdir().expect("tempdir");
        {
            let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
            journal
                .append("one", "Edit", b"saved".to_vec())
                .expect("append");
            journal
                .checkpoint(1, "loom.test/1", b"saved")
                .expect("checkpoint");
        }
        let mut reopened = RecoveryJournal::open(temporary.path()).expect("reopen");
        let record = reopened
            .append("two", "Edit", b"unsaved".to_vec())
            .expect("append after checkpoint");
        assert_eq!(record.sequence, 2);
        assert_eq!(reopened.recover().expect("recover").operations.len(), 1);
    }

    #[test]
    fn journal_sequence_overflow_is_reported() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let metadata = CheckpointMetadata {
            last_sequence: u64::MAX,
            sha256: sha256_hex(b"checkpoint"),
            timestamp_ms: unix_time_ms(),
            schema: "loom.test/1".into(),
        };
        fs::write(
            temporary.path().join(CHECKPOINT_META_FILE),
            serde_json::to_vec(&metadata).expect("metadata"),
        )
        .expect("write metadata");
        fs::write(temporary.path().join(CHECKPOINT_FILE), b"checkpoint").expect("write checkpoint");
        let error = RecoveryJournal::open(temporary.path()).expect_err("overflow must fail");
        assert!(format!("{error}").contains("exhausted"));
    }

    #[test]
    fn crash_during_append_leaves_torn_tail_that_recovers_and_self_heals() {
        let temporary = tempfile::tempdir().expect("tempdir");
        {
            let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
            for sequence in 1..=3 {
                journal
                    .append("op", "Edit", format!("payload-{sequence}").into_bytes())
                    .expect("append");
            }
            // Simulate a crash interrupting a fourth append: a torn line that
            // was never synced to disk.
            let journal_path = temporary.path().join(JOURNAL_FILE);
            let mut file = OpenOptions::new()
                .append(true)
                .open(&journal_path)
                .expect("open journal");
            file.write_all(b"{\"sequence\": 4,").expect("torn write");
            file.sync_data().expect("sync torn tail");
        }
        // New process: open must tolerate the torn tail and repair the file.
        let mut journal = RecoveryJournal::open(temporary.path()).expect("reopen after crash");
        assert_eq!(journal.records().expect("records").len(), 3);
        let state = journal.recover().expect("recover");
        assert_eq!(state.operations.len(), 3);
        assert_eq!(state.operations[2].payload.as_slice(), b"payload-3");
        // Appending after repair writes a clean record 4.
        journal
            .append("op", "Edit", b"payload-4".to_vec())
            .expect("append after repair");
        let journal_path = temporary.path().join(JOURNAL_FILE);
        let final_lines = fs::read_to_string(journal_path).expect("read repaired journal");
        assert_eq!(final_lines.lines().count(), 4);
        assert!(journal.records().expect("records").len() == 4);
        let reopened = RecoveryJournal::open(temporary.path()).expect("final reopen");
        assert_eq!(
            reopened.records().expect("records")[3].payload.as_slice(),
            b"payload-4"
        );
    }

    #[test]
    fn corrupt_checkpoint_fails_bounded_without_panicking() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let mut journal = RecoveryJournal::open(temporary.path()).expect("journal");
        journal
            .append("one", "Edit", b"first".to_vec())
            .expect("append");
        journal
            .checkpoint(1, "loom.test/1", b"checkpoint")
            .expect("checkpoint");

        // Corrupt the active commit pointer on every platform. On Windows,
        // new checkpoints live behind uniquely named commit files; the legacy
        // checkpoint.json file is not the authoritative pointer there.
        #[cfg(windows)]
        let pointer_path = {
            let pointer = read_latest_commit_pointer(temporary.path())
                .expect("read published pointer")
                .expect("published checkpoint");
            temporary.path().join(format!(
                "{CHECKPOINT_COMMIT_PREFIX}{}{CHECKPOINT_COMMIT_SUFFIX}",
                pointer.generation
            ))
        };
        #[cfg(not(windows))]
        let pointer_path = temporary.path().join(CHECKPOINT_META_FILE);

        let valid_pointer = fs::read(&pointer_path).expect("read active pointer");
        let pointer: CheckpointPointer =
            serde_json::from_slice(&valid_pointer).expect("decode active pointer");

        // Garbage commit-pointer JSON must be a bounded error, never a panic.
        fs::write(&pointer_path, b"{\"not\": \"json\"\"").expect("corrupt pointer");
        let outcome = journal.recover();
        let error = match &outcome {
            Err(error) => format!("{error}"),
            Ok(_) => panic!("corrupt checkpoint pointer must not recover"),
        };
        assert!(
            error.contains("checkpoint") || error.to_lowercase().contains("json"),
            "error should describe the damaged checkpoint: {error}"
        );

        // Restore the commit pointer, then corrupt the referenced payload.
        fs::write(&pointer_path, valid_pointer).expect("restore pointer");
        fs::write(
            checkpoint_generation_payload_path(temporary.path(), pointer.generation),
            b"garbage",
        )
        .expect("torn payload");
        let outcome = journal.recover();
        assert!(
            matches!(outcome, Err(ProductionError::Integrity(_))),
            "torn checkpoint payload must be a bounded integrity error"
        );
    }

    #[test]
    fn locale_fallback_and_arguments_are_deterministic() {
        let mut catalog = LocaleCatalog::new("en");
        catalog
            .load_json("en", r#"{"save":"Save {name}","open":"Open"}"#)
            .expect("English");
        catalog
            .load_json("fr", r#"{"open":"Ouvrir"}"#)
            .expect("French");
        assert_eq!(catalog.resolve("fr-CA", "open"), Some("Ouvrir"));
        assert_eq!(catalog.resolve("fr-CA", "save"), Some("Save {name}"));
        let arguments = BTreeMap::from([("name".into(), "Project".into())]);
        assert_eq!(
            catalog.format("fr-CA", "save", &arguments).as_deref(),
            Some("Save Project")
        );
    }

    #[test]
    fn profiler_computes_percentiles() {
        let recorder = TraceRecorder::default();
        for milliseconds in 1..=100 {
            recorder
                .record("preview", Duration::from_millis(milliseconds))
                .expect("record");
        }
        let summary = recorder.summary("preview").expect("summary").expect("data");
        assert_eq!(summary.count, 100);
        assert_eq!(summary.p50, Duration::from_millis(51));
        assert_eq!(summary.p95, Duration::from_millis(96));
        assert_eq!(summary.p99, Duration::from_millis(100));
    }

    #[test]
    fn accessibility_audit_reports_actionable_rules() {
        let node = AccessibilityNode {
            id: "save".into(),
            role: "button".into(),
            label: "".into(),
            description: String::new(),
            width: 18.0,
            height: 18.0,
            foreground_luminance: 0.4,
            background_luminance: 0.5,
            keyboard_focusable: false,
        };
        let rules: BTreeSet<String> = audit_accessibility(&[node])
            .into_iter()
            .map(|finding| finding.rule)
            .collect();
        assert!(rules.contains("label.required"));
        assert!(rules.contains("target.minimum"));
        assert!(rules.contains("keyboard.reachable"));
        assert!(rules.contains("contrast.normal-text"));
    }

    #[test]
    fn release_matrix_requires_all_primary_platforms() {
        let errors = validate_release_matrix(&[InstallerTarget {
            operating_system: OperatingSystem::Linux,
            architecture: Architecture::X86_64,
            package_kind: "appimage".into(),
            signing_required: false,
            updates_supported: true,
        }]);
        assert_eq!(errors.len(), 2);
    }
}
