//! Excel worksheet function inventory (spike C).
//!
//! The reference list is Microsoft's alphabetical function list: 521 names, which
//! include the DBCS byte variants (FINDB, LEFTB, LENB, MIDB, REPLACEB, RIGHTB,
//! SEARCHB) that Loom does not implement separately, and the legacy names.
//! A name is supported when `=NAME()` and `=NAME(1,2)` do not return `#NAME?`.
//! Before spike C: 126 supported and 395 missing. The table below is generated from
//! the evaluator, and `tests/function_inventory_tests.rs` fails if the supported
//! count falls below the recorded floor.
//!
//! Category | Names | Supported | Missing
//! --- | ---: | ---: | ---:
//! Math and trigonometry | 79 | 26 | 53
//! Statistical | 109 | 33 | 76
//! Compatibility (legacy statistical names) | 40 | 7 | 33
//! Financial | 55 | 15 | 40
//! Date and time | 25 | 23 | 2
//! Text | 48 | 25 | 23
//! Logical | 13 | 11 | 2
//! Lookup and reference | 17 | 8 | 9
//! Information | 21 | 8 | 13
//! Engineering | 54 | 0 | 54
//! Database | 12 | 0 | 12
//! Cube (external OLAP; out of scope) | 7 | 0 | 7
//! Web, add-in and external data (out of scope) | 11 | 0 | 11
//! Dynamic arrays and LAMBDA (Excel 365) | 30 | 19 | 11
//! All reference names | 521 | 175 | 346
//!
//! Missing names by category:
//!
//! Math and trigonometry (53): ACOS, ACOSH, ACOT, ACOTH, AGGREGATE, ARABIC, ASIN, ASINH,
//! ATAN, ATAN2, ATANH, BASE, CEILING.MATH, CEILING.PRECISE, COMBIN, COMBINA, COS, COSH,
//! COT, COTH, CSC, CSCH, DECIMAL, DEGREES, EVEN, FACT, FACTDOUBLE, FLOOR.MATH,
//! FLOOR.PRECISE, GCD, ISO.CEILING, LCM, MDETERM, MINVERSE, MMULT, MULTINOMIAL, MUNIT,
//! ODD, RADIANS, ROMAN, SEC, SECH, SERIESSUM, SIN, SINH, SQRTPI, SUBTOTAL, SUMSQ,
//! SUMX2MY2, SUMX2PY2, SUMXMY2, TAN, TANH.
//!
//! Statistical (76): AVEDEV, AVERAGEA, BETA.DIST, BETA.INV, BINOM.DIST, BINOM.DIST.RANGE,
//! BINOM.INV, CHISQ.DIST, CHISQ.DIST.RT, CHISQ.INV, CHISQ.INV.RT, CHISQ.TEST,
//! CONFIDENCE.NORM, CONFIDENCE.T, COVARIANCE.P, COVARIANCE.S, DEVSQ, EXPON.DIST, F.DIST,
//! F.DIST.RT, F.INV, F.INV.RT, F.TEST, FISHER, FISHERINV, FORECAST.ETS,
//! FORECAST.ETS.CONFINT, FORECAST.ETS.SEASONALITY, FORECAST.ETS.STAT, FREQUENCY, GAMMA,
//! GAMMA.DIST, GAMMA.INV, GAMMALN.PRECISE, GAUSS, GEOMEAN, HARMEAN, HYPGEOM.DIST, KURT,
//! LINEST, LOGEST, LOGNORM.DIST, LOGNORM.INV, MAXA, MINA, MODE.MULT, NEGBINOM.DIST,
//! NORM.DIST, NORM.INV, NORM.S.DIST, NORM.S.INV, PEARSON, PERMUT, PERMUTATIONA, PHI,
//! POISSON.DIST, PROB, RSQ, SKEW, SKEW.P, STANDARDIZE, STDEVA, STEYX, T.DIST, T.DIST.2T,
//! T.DIST.RT, T.INV, T.INV.2T, T.TEST, TREND, TRIMMEAN, VARA, VARPA, WEIBULL.DIST, Z.TEST,
//! GROWTH.
//!
//! Compatibility (legacy statistical names) (33): BETADIST, BETAINV, BINOMDIST, CHIDIST,
//! CHIINV, CHITEST, CONFIDENCE, COVAR, CRITBINOM, EXPONDIST, FDIST, FINV, FTEST,
//! GAMMADIST, GAMMAINV, GAMMALN, HYPGEOMDIST, LOGINV, LOGNORMDIST, NEGBINOMDIST, NORMDIST,
//! NORMINV, NORMSDIST, NORMSINV, POISSON, STDEVP, TDIST, TINV, TTEST, VARP, WEIBULL,
//! ZTEST, STDEVPA.
//!
//! Financial (40): ACCRINT, ACCRINTM, AMORDEGRC, AMORLINC, COUPDAYBS, COUPDAYS,
//! COUPDAYSNC, COUPNCD, COUPNUM, COUPPCD, CUMIPMT, CUMPRINC, DISC, DOLLARDE, DOLLARFR,
//! DURATION, EFFECT, FVSCHEDULE, INTRATE, ISPMT, MDURATION, MIRR, NOMINAL, ODDFPRICE,
//! ODDFYIELD, ODDLPRICE, ODDLYIELD, PDURATION, PRICE, PRICEDISC, PRICEMAT, RECEIVED, RRI,
//! TBILLEQ, TBILLPRICE, TBILLYIELD, VDB, YIELD, YIELDDISC, YIELDMAT.
//!
//! Date and time (2): DAYS360, TIMEVALUE.
//!
//! Text (23): ASC, BAHTTEXT, DBCS, DOLLAR, FINDB, FIXED, JIS, LEFTB, LENB, MIDB,
//! NUMBERVALUE, PHONETIC, REPLACEB, RIGHTB, SEARCHB, T, UNICHAR, UNICODE, VALUETOTEXT,
//! ARRAYTOTEXT, REGEXEXTRACT, REGEXREPLACE, REGEXTEST.
//!
//! Logical (2): LAMBDA, NOT.
//!
//! Lookup and reference (9): ADDRESS, AREAS, COLUMN, GETPIVOTDATA, HYPERLINK, INDIRECT,
//! LOOKUP, OFFSET, ROW.
//!
//! Information (13): CELL, ERROR.TYPE, INFO, ISERR, ISEVEN, ISFORMULA, ISNONTEXT, ISODD,
//! ISREF, SHEET, SHEETS, TYPE, FORMULATEXT.
//!
//! Engineering (54): BESSELI, BESSELJ, BESSELK, BESSELY, BIN2DEC, BIN2HEX, BIN2OCT,
//! BITAND, BITLSHIFT, BITOR, BITRSHIFT, BITXOR, COMPLEX, CONVERT, DEC2BIN, DEC2HEX,
//! DEC2OCT, DELTA, ERF, ERF.PRECISE, ERFC, ERFC.PRECISE, GESTEP, HEX2BIN, HEX2DEC,
//! HEX2OCT, IMABS, IMAGINARY, IMARGUMENT, IMCONJUGATE, IMCOS, IMCOSH, IMCOT, IMCSC,
//! IMCSCH, IMDIV, IMEXP, IMLN, IMLOG10, IMLOG2, IMPOWER, IMPRODUCT, IMREAL, IMSEC, IMSECH,
//! IMSIN, IMSINH, IMSQRT, IMSUB, IMSUM, IMTAN, OCT2BIN, OCT2DEC, OCT2HEX.
//!
//! Database (12): DAVERAGE, DCOUNT, DCOUNTA, DGET, DMAX, DMIN, DPRODUCT, DSTDEV, DSTDEVP,
//! DSUM, DVAR, DVARP.
//!
//! Cube (external OLAP; out of scope) (7): CUBEKPIMEMBER, CUBEMEMBER, CUBEMEMBERPROPERTY,
//! CUBERANKEDMEMBER, CUBESET, CUBESETCOUNT, CUBEVALUE.
//!
//! Web, add-in and external data (out of scope) (11): CALL, ENCODEURL, EUROCONVERT,
//! FILTERXML, IMAGE, REGISTER.ID, STOCKHISTORY, WEBSERVICE, DETECTLANGUAGE, TRANSLATE, RTD.
//!
//! Dynamic arrays and LAMBDA (Excel 365) (11): BYCOL, BYROW, GROUPBY, ISOMITTED,
//! MAKEARRAY, MAP, PERCENTOF, PIVOTBY, REDUCE, SCAN, TRIMRANGE.
//!
